export const FIFTEEN_MINUTES_IN_MS = 60 * 15 * 1000
export const FIFTEEN_MINUTES_IN_SECONDS = FIFTEEN_MINUTES_IN_MS / 1000

export const THIRTY_MINUTES_IN_MS = FIFTEEN_MINUTES_IN_MS * 2
export const THIRTY_MINUTES_IN_SECONDS = THIRTY_MINUTES_IN_MS / 1000

export const DAY_IN_MS = THIRTY_MINUTES_IN_MS * 2 * 24

export const WEEK_IN_MS = DAY_IN_MS * 7
export const WEEK_IN_SECONDS = WEEK_IN_MS / 1000
