export const products = [
  {
    title: 'Bradley 3 Seat Bench Teak Brown/Beige',
    category: 'outdoor',
    prevPrice: '360.00',
    subCategory: 'benches',
    price: '289.00',
  },
  {
    title: 'Kane Acacia Bench Natural',
    category: 'outdoor',
    prevPrice: '430.00',
    subCategory: 'benches',
    price: '349.00',
  },
  {
    title: 'Bradley 3 Seat Bench Dark Slate Gray/Beige',
    category: 'outdoor',
    prevPrice: '380.00',
    subCategory: 'benches',
    price: '299.00',
  },
  {
    title: 'Deco Mar 3 Seat Bench Teak Brown/Beige',
    category: 'outdoor',
    prevPrice: '360.00',
    subCategory: 'benches',
    price: '289.00',
  },
  {
    title: 'Poliano 2 Seat Bench Ash Gray',
    category: 'outdoor',
    prevPrice: '240.00',
    subCategory: 'benches',
    price: '189.00',
  },
  {
    title: 'Poliano 2 Seat Bench Teak',
    category: 'outdoor',
    prevPrice: '230.00',
    subCategory: 'benches',
    price: '179.00',
  },
  {
    title: 'Eleni Large Cushion Box Gray Wash',
    category: 'outdoor',
    prevPrice: '300.00',
    subCategory: 'benches',
    price: '239.00',
  },
  {
    title: 'Bradley 3 Seat Bench Ash Gray/Beige',
    category: 'outdoor',
    prevPrice: '380.00',
    subCategory: 'benches',
    price: '299.00',
  },
  {
    title: 'Kane Acacia Bench Ash Gray',
    category: 'outdoor',
    prevPrice: '460.00',
    subCategory: 'benches',
    price: '369.00',
  },
  {
    title: 'Brantley Twin Seat Bench Teak Brown',
    category: 'outdoor',
    prevPrice: '280.00',
    subCategory: 'benches',
    price: '219.00',
  },
  {
    title: 'Brantley Twin Seat Bench Gray',
    category: 'outdoor',
    prevPrice: '270.00',
    subCategory: 'benches',
    price: '219.00',
  },
  {
    title: 'Halyn Acacia Bench Dark Slate Gray',
    category: 'outdoor',
    prevPrice: '380.00',
    subCategory: 'benches',
    price: '299.00',
  },
  {
    title: 'Maribel Outdoor Bench Dark Slate Gray',
    category: 'outdoor',
    prevPrice: '240.00',
    subCategory: 'benches',
    price: '199.00',
  },
  {
    title: 'Maribel Outdoor Bench White',
    category: 'outdoor',
    prevPrice: '260.00',
    subCategory: 'benches',
    price: '199.00',
  },
  {
    title: 'Infinite Acacia Bench Dark Slate Gray',
    category: 'outdoor',
    prevPrice: '350.00',
    subCategory: 'benches',
    price: '279.00',
  },
  {
    title: 'Halyn Acacia Bench Natural',
    category: 'outdoor',
    prevPrice: '360.00',
    subCategory: 'benches',
    price: '289.00',
  },
  {
    title: 'Halyn Acacia Bench White',
    category: 'outdoor',
    prevPrice: '429.00',
    subCategory: 'benches',
    price: '349.00',
  },
  {
    title: 'Eleni Large Cushion Box Teak',
    category: 'outdoor',
    prevPrice: '290.00',
    subCategory: 'benches',
    price: '239.00',
  },
  {
    title: 'Deco Mar 3 Seat Bench Ash Gray/Beige',
    category: 'outdoor',
    prevPrice: '390.00',
    subCategory: 'benches',
    price: '299.00',
  },
  {
    title: 'Brent Storage Bench Distressed White',
    category: 'outdoor',
    prevPrice: '470.00',
    subCategory: 'benches',
    price: '379.00',
  },
  {
    title: 'Brent Storage Bench Teak Brown',
    category: 'outdoor',
    prevPrice: '380.00',
    subCategory: 'benches',
    price: '299.00',
  },
  {
    title: 'Brent Storage Bench Gray',
    category: 'outdoor',
    prevPrice: '470.00',
    subCategory: 'benches',
    price: '379.00',
  },
  {
    title: 'Abey Large Cushion Box Gray Wash',
    category: 'outdoor',
    prevPrice: '320.00',
    subCategory: 'benches',
    price: '249.00',
  },
  {
    title: 'Abey Large Cushion Box Teak',
    category: 'outdoor',
    prevPrice: '290.00',
    subCategory: 'benches',
    price: '229.00',
  },
  {
    title: 'Montrelle Acacia Chair White',
    category: 'outdoor',
    prevPrice: '200.00',
    subCategory: 'lounge-chairs',
    price: '159.00',
  },
  {
    title: 'Azahar Acacia Sunlounger Teak Brown/Beige',
    category: 'outdoor',
    prevPrice: '420.00',
    subCategory: 'lounge-chairs',
    price: '349.00',
  },
  {
    title: 'Montrelle Acacia Ottoman White',
    category: 'outdoor',
    prevPrice: '90.00',
    subCategory: 'lounge-chairs',
    price: '79.00',
  },
  {
    title: 'Montrelle Acacia Chair Ash Gray',
    category: 'outdoor',
    prevPrice: '199.00',
    subCategory: 'lounge-chairs',
    price: '159.00',
  },
  {
    title: 'Violetta Wine Glass Holder Adirondack Chair Ash Gray',
    category: 'outdoor',
    prevPrice: '199.00',
    subCategory: 'lounge-chairs',
    price: '159.00',
  },
  {
    title: 'Violetta Wine Glass Holder Adirondack Chair Dark Slate Gray',
    category: 'outdoor',
    prevPrice: '199.00',
    subCategory: 'lounge-chairs',
    price: '159.00',
  },
  {
    title: 'Bamboo Rocking Chair Dark Slate Gray',
    category: 'outdoor',
    prevPrice: '190.00',
    subCategory: 'lounge-chairs',
    price: '149.00',
  },
  {
    title: 'Monty Rocking Chair Teak Brown',
    category: 'outdoor',
    prevPrice: '190.00',
    subCategory: 'lounge-chairs',
    price: '149.00',
  },
  {
    title: 'Montrelle Acacia Chair Natural',
    category: 'outdoor',
    prevPrice: '190.00',
    subCategory: 'lounge-chairs',
    price: '149.00',
  },
  {
    title: 'Torrance Adirondack Chair Teak',
    category: 'outdoor',
    prevPrice: '170.00',
    subCategory: 'lounge-chairs',
    price: '139.00',
  },
  {
    title: 'Venus Rocking Chair Black/White',
    category: 'outdoor',
    prevPrice: '280.00',
    subCategory: 'lounge-chairs',
    price: '219.00',
  },
  {
    title: 'Lalita Adirondack Chair Teak',
    category: 'outdoor',
    prevPrice: '200.00',
    subCategory: 'lounge-chairs',
    price: '159.00',
  },
  {
    title: 'Solstice Sunlounger Teak Brown/Beige',
    category: 'outdoor',
    prevPrice: '429.00',
    subCategory: 'lounge-chairs',
    price: '349.00',
  },
  {
    title: 'Modern Acacia Sunlounger Ash Gray/Beige',
    category: 'outdoor',
    prevPrice: '450.00',
    subCategory: 'lounge-chairs',
    price: '359.00',
  },
  {
    title: 'Lachlyn Director Chair Gray Wash/Navy (Set of 2)',
    category: 'outdoor',
    prevPrice: '190.00',
    subCategory: 'lounge-chairs',
    price: '149.00',
  },
  {
    title: 'Modern Acacia Sunlounger Dark Slate Gray/Beige',
    category: 'outdoor',
    prevPrice: '450.00',
    subCategory: 'lounge-chairs',
    price: '359.00',
  },
  {
    title: 'Azahar Acacia Sunlounger Dark Slate Gray/Beige',
    category: 'outdoor',
    prevPrice: '450.00',
    subCategory: 'lounge-chairs',
    price: '359.00',
  },
  {
    title: 'Lachlyn Director Chair Teak/Yellow (Set of 2)',
    category: 'outdoor',
    prevPrice: '180.00',
    subCategory: 'lounge-chairs',
    price: '139.00',
  },
  {
    title: 'Torrance Adirondack Chair Gray Wash',
    category: 'outdoor',
    prevPrice: '200.00',
    subCategory: 'lounge-chairs',
    price: '159.00',
  },
  {
    title: 'Venus Rocking Chair Gray/Beige',
    category: 'outdoor',
    prevPrice: '280.00',
    subCategory: 'lounge-chairs',
    price: '219.00',
  },
  {
    title: 'Venus Rocking Chair Teak Brown/Gray',
    category: 'outdoor',
    prevPrice: '280.00',
    subCategory: 'lounge-chairs',
    price: '229.00',
  },
  {
    title: 'Venus Rocking Chair Teak Brown/Navy',
    category: 'outdoor',
    prevPrice: '280.00',
    subCategory: 'lounge-chairs',
    price: '229.00',
  },
  {
    title: 'Venus Rocking Chair Teak Brown/Yellow',
    category: 'outdoor',
    prevPrice: '280.00',
    subCategory: 'lounge-chairs',
    price: '229.00',
  },
  {
    title: 'Venus Rocking Chair Teak Brown/Beige',
    category: 'outdoor',
    prevPrice: '280.00',
    subCategory: 'lounge-chairs',
    price: '229.00',
  },
  {
    title: 'Sora Rocking Chair Teak Brown',
    category: 'outdoor',
    prevPrice: '420.00',
    subCategory: 'lounge-chairs',
    price: '339.00',
  },
  {
    title: 'Sora Rocking Chair Ash Gray',
    category: 'outdoor',
    prevPrice: '440.00',
    subCategory: 'lounge-chairs',
    price: '349.00',
  },
  {
    title: 'Solstice Sunlounger Teak Brown/Navy',
    category: 'outdoor',
    prevPrice: '429.00',
    subCategory: 'lounge-chairs',
    price: '349.00',
  },
  {
    title: 'Solstice Sunlounger Teak Brown/Yellow',
    category: 'outdoor',
    prevPrice: '429.00',
    subCategory: 'lounge-chairs',
    price: '349.00',
  },
  {
    title: 'Shag Rocking Chair White Wash',
    category: 'outdoor',
    prevPrice: '190.00',
    subCategory: 'lounge-chairs',
    price: '149.00',
  },
  {
    title: 'Shag Rocking Chair Gray Wash',
    category: 'outdoor',
    prevPrice: '190.00',
    subCategory: 'lounge-chairs',
    price: '149.00',
  },
  {
    title: 'Shag Rocking Chair Teak',
    category: 'outdoor',
    prevPrice: '190.00',
    subCategory: 'lounge-chairs',
    price: '149.00',
  },
  {
    title: 'Rigby Foldable Sling Chair White Wash/Navy',
    category: 'outdoor',
    prevPrice: '180.00',
    subCategory: 'lounge-chairs',
    price: '139.00',
  },
  {
    title: 'Palm Lounge Chair Gray/Navy',
    category: 'outdoor',
    prevPrice: '250.00',
    subCategory: 'lounge-chairs',
    price: '199.00',
  },
  {
    title: 'Palm Lounge Chair Teak Brown/Navy',
    category: 'outdoor',
    prevPrice: '240.00',
    subCategory: 'lounge-chairs',
    price: '189.00',
  },
  {
    title: 'Neptune Chaise Lounge Chair With Side Table Teak Brown/Navy',
    category: 'outdoor',
    prevPrice: '490.00',
    subCategory: 'lounge-chairs',
    price: '399.00',
  },
  {
    title: 'Montrelle Acacia Ottoman Dark Slate Gray',
    category: 'outdoor',
    prevPrice: '120.00',
    subCategory: 'lounge-chairs',
    price: '99.00',
  },
  {
    title: 'Montrelle Acacia Ottoman Ash Gray',
    category: 'outdoor',
    prevPrice: '120.00',
    subCategory: 'lounge-chairs',
    price: '99.00',
  },
  {
    title: 'Montrelle Acacia Chair Dark Slate Gray',
    category: 'outdoor',
    prevPrice: '199.00',
    subCategory: 'lounge-chairs',
    price: '159.00',
  },
  {
    title: 'Montrelle Acacia Chair Off White',
    category: 'outdoor',
    prevPrice: '200.00',
    subCategory: 'lounge-chairs',
    price: '159.00',
  },
  {
    title: 'Montrelle Acacia Chair Teal',
    category: 'outdoor',
    prevPrice: '200.00',
    subCategory: 'lounge-chairs',
    price: '159.00',
  },
  {
    title: 'Manor Lounge Chair Dark Slate Gray',
    category: 'outdoor',
    prevPrice: '290.00',
    subCategory: 'lounge-chairs',
    price: '229.00',
  },
  {
    title: 'Manor Lounge Chair Ash Gray',
    category: 'outdoor',
    prevPrice: '290.00',
    subCategory: 'lounge-chairs',
    price: '229.00',
  },
  {
    title: 'Manor Lounge Chair Teak Brown',
    category: 'outdoor',
    prevPrice: '280.00',
    subCategory: 'lounge-chairs',
    price: '219.00',
  },
  {
    title: 'Lombardi Foldable Sling Chair Teak/Black/White (Set of 2)',
    category: 'outdoor',
    prevPrice: '220.00',
    subCategory: 'lounge-chairs',
    price: '179.00',
  },
  {
    title: 'Eloise Mesh Office Chair Black',
    category: 'office',
    prevPrice: '310.00',
    subCategory: 'office-chairs',
    price: '249.00',
  },
  {
    title: 'Eloise Vinyl Office Chair Tan',
    category: 'office',
    prevPrice: '300.00',
    subCategory: 'office-chairs',
    price: '239.00',
  },
  {
    title: 'Jaxon Mid Back Office Chair Terracotta',
    category: 'office',
    prevPrice: '490.00',
    subCategory: 'office-chairs',
    price: '399.00',
  },
  {
    title: 'Jaxon Mid Back Office Chair White',
    category: 'office',
    prevPrice: '500.00',
    subCategory: 'office-chairs',
    price: '399.00',
  },
  {
    title: 'Christina Mesh Office Chair Black',
    category: 'office',
    prevPrice: '330.00',
    subCategory: 'office-chairs',
    price: '269.00',
  },
  {
    title: 'Carla Office Chair Black',
    category: 'office',
    prevPrice: '280.00',
    subCategory: 'office-chairs',
    price: '219.00',
  },
  {
    title: 'Adena Office Chair Black',
    category: 'office',
    prevPrice: '220.00',
    subCategory: 'office-chairs',
    price: '179.00',
  },
  {
    title: 'Fisher Mid Back Office Chair Black',
    category: 'office',
    prevPrice: '350.00',
    subCategory: 'office-chairs',
    price: '279.00',
  },
  {
    title: 'Arlo Mesh Office Chair Black',
    category: 'office',
    prevPrice: '300.00',
    subCategory: 'office-chairs',
    price: '239.00',
  },
  {
    title: 'Eloise Vinyl Office Chair White',
    category: 'office',
    prevPrice: '320.00',
    subCategory: 'office-chairs',
    price: '259.00',
  },
  {
    title: 'Atlas Office Chair Black',
    category: 'office',
    prevPrice: '270.00',
    subCategory: 'office-chairs',
    price: '219.00',
  },
  {
    title: 'Partridge Mesh Office Chair Black',
    category: 'office',
    prevPrice: '230.00',
    subCategory: 'office-chairs',
    price: '179.00',
  },
  {
    title: 'Vincent Mesh Office Chair Red',
    category: 'office',
    prevPrice: '250.00',
    subCategory: 'office-chairs',
    price: '199.00',
  },
  {
    title: 'Whalen Faux Sheepskin Gold Leg Swivel Chair',
    category: 'office',
    prevPrice: '350.00',
    subCategory: 'office-chairs',
    price: '279.00',
  },
  {
    title: 'Partridge Vinyl Office Office Chair Black',
    category: 'office',
    prevPrice: '230.00',
    subCategory: 'office-chairs',
    price: '179.00',
  },
  {
    title: 'Vincent Mesh Office Chair Black',
    category: 'office',
    prevPrice: '240.00',
    subCategory: 'office-chairs',
    price: '189.00',
  },
  {
    title: 'Fisher Highback Office Chair White',
    category: 'office',
    prevPrice: '430.00',
    subCategory: 'office-chairs',
    price: '349.00',
  },
  {
    title: 'Eloise All Mesh Office Chair Gray',
    category: 'office',
    prevPrice: '360.00',
    subCategory: 'office-chairs',
    price: '289.00',
  },
  {
    title: 'Bordeaux Office Swivel Chair Green',
    category: 'office',
    prevPrice: '690.00',
    subCategory: 'office-chairs',
    price: '559.00',
  },
  {
    title: 'Fisher Mid Back Office Chair White',
    category: 'office',
    prevPrice: '350.00',
    subCategory: 'office-chairs',
    price: '279.00',
  },
  {
    title: 'Amalya Tufted Linen Office Chair Gray/Chrome',
    category: 'office',
    prevPrice: '360.00',
    subCategory: 'office-chairs',
    price: '289.00',
  },
  {
    title: 'Iago Linen Chrome Leg Swivel Office Chair Gray/Chrome',
    category: 'office',
    prevPrice: '599.00',
    subCategory: 'office-chairs',
    price: '479.00',
  },
  {
    title: 'Amalya Tufted Velvet Office Chair Navy/Chrome',
    category: 'office',
    prevPrice: '360.00',
    subCategory: 'office-chairs',
    price: '289.00',
  },
  {
    title: 'Flynn Swivel Office Chair Beige',
    category: 'office',
    prevPrice: '260.00',
    subCategory: 'office-chairs',
    price: '219.00',
  },
  {
    title: 'Eloise Mesh Office Chair Gray',
    category: 'office',
    prevPrice: '310.00',
    subCategory: 'office-chairs',
    price: '249.00',
  },
  {
    title: 'Whalen Faux Sheepskin Chrome Leg Swivel Chair',
    category: 'office',
    prevPrice: '350.00',
    subCategory: 'office-chairs',
    price: '279.00',
  },
  {
    title: 'Arlo Mesh Office Chair Gray',
    category: 'office',
    prevPrice: '300.00',
    subCategory: 'office-chairs',
    price: '239.00',
  },
  {
    title: 'Evelyn Tufted Linen Swivel Office Chair',
    category: 'office',
    prevPrice: '370.00',
    subCategory: 'office-chairs',
    price: '299.00',
  },
  {
    title: 'Eloise Vinyl Office Chair Black',
    category: 'office',
    prevPrice: '300.00',
    subCategory: 'office-chairs',
    price: '239.00',
  },
  {
    title: 'Christina Mesh Office Chair Gray',
    category: 'office',
    prevPrice: '330.00',
    subCategory: 'office-chairs',
    price: '269.00',
  },
  {
    title: 'Adele Velvet Chrome Leg Swivel Office Chair',
    category: 'office',
    prevPrice: '370.00',
    subCategory: 'office-chairs',
    price: '299.00',
  },
  {
    title: 'Adele Linen Chrome Leg Swivel Office Chair',
    category: 'office',
    prevPrice: '370.00',
    subCategory: 'office-chairs',
    price: '299.00',
  },
  {
    title: 'Evelyn Tufted Velvet Swivel Office Chair',
    category: 'office',
    prevPrice: '369.00',
    subCategory: 'office-chairs',
    price: '299.00',
  },
  {
    title: 'Flynn Swivel Office Chair Brown',
    category: 'office',
    prevPrice: '240.00',
    subCategory: 'office-chairs',
    price: '189.00',
  },
  {
    title: 'Eloise Mesh Office Chair White',
    category: 'office',
    prevPrice: '310.00',
    subCategory: 'office-chairs',
    price: '249.00',
  },
  {
    title: 'Farmington Mesh Office Chair Black',
    category: 'office',
    prevPrice: '300.00',
    subCategory: 'office-chairs',
    price: '239.00',
  },
  {
    title: 'Emanuel Office Chair Light Brown/Black',
    category: 'office',
    prevPrice: '549.00',
    subCategory: 'office-chairs',
    price: '439.00',
  },
  {
    title: 'Surge Desk Walnut',
    category: 'office',
    prevPrice: '480.00',
    subCategory: 'desks',
    price: '389.00',
  },
  {
    title: 'Paisley 2 Drawer Desk',
    category: 'office',
    prevPrice: '250.00',
    subCategory: 'desks',
    price: '199.00',
  },
  {
    title: 'Bjorn Desk Walnut',
    category: 'office',
    prevPrice: '210.00',
    subCategory: 'desks',
    price: '169.00',
  },
  {
    title: 'Bjorn Desk Oak',
    category: 'office',
    prevPrice: '210.00',
    subCategory: 'desks',
    price: '169.00',
  },
  {
    title: 'Pan Desk Birch',
    category: 'office',
    prevPrice: '290.00',
    subCategory: 'desks',
    price: '239.00',
  },
  {
    title: 'Curation Writing Desk',
    category: 'office',
    prevPrice: '230.00',
    subCategory: 'desks',
    price: '189.00',
  },
  {
    title: 'Turn Desk Birch',
    category: 'office',
    prevPrice: '240.00',
    subCategory: 'desks',
    price: '199.00',
  },
  {
    title: 'Section Office Desk White',
    category: 'office',
    prevPrice: '760.00',
    subCategory: 'desks',
    price: '619.00',
  },
  {
    title: 'Section Office Desk White/Gold',
    category: 'office',
    prevPrice: '810.00',
    subCategory: 'desks',
    price: '649.00',
  },
  {
    title: 'Maddison 2-Drawer Lacquer Desk White/Gold',
    category: 'office',
    prevPrice: '1,300.00',
    subCategory: 'desks',
    price: '1,049.00',
  },
  {
    title: 'Joe 1 Drawer 1 Shelf Desk Natural/White',
    category: 'office',
    prevPrice: '260.00',
    subCategory: 'desks',
    price: '199.00',
  },
  {
    title: 'Chelsea Office Desk White/Walnut',
    category: 'office',
    prevPrice: '540.00',
    subCategory: 'desks',
    price: '429.00',
  },
  {
    title: 'Stuy Office Desk Oak',
    category: 'office',
    prevPrice: '320.00',
    subCategory: 'desks',
    price: '249.00',
  },
  {
    title: 'Paula 1 Drawer Desk',
    category: 'office',
    prevPrice: '430.00',
    subCategory: 'desks',
    price: '349.00',
  },
  {
    title: 'Remma 1 Drawer Writing Desk Distressed White',
    category: 'office',
    prevPrice: '260.00',
    subCategory: 'desks',
    price: '199.00',
  },
  {
    title: 'Suspension Office Desk White',
    category: 'office',
    prevPrice: '620.00',
    subCategory: 'desks',
    price: '499.00',
  },
  {
    title: 'Alena Lacquer One Drawer Vanity Desk',
    category: 'office',
    prevPrice: '580.00',
    subCategory: 'desks',
    price: '469.00',
  },
  {
    title: 'Bjorn Desk Cherry',
    category: 'office',
    prevPrice: '210.00',
    subCategory: 'desks',
    price: '169.00',
  },
  {
    title: 'Noemi Coastal Writing Desk Brown',
    category: 'office',
    prevPrice: '700.00',
    subCategory: 'desks',
    price: '569.00',
  },
  {
    title: 'Paloma 2 Shelf Leaning Desk White',
    category: 'office',
    prevPrice: '270.00',
    subCategory: 'desks',
    price: '219.00',
  },
  {
    title: 'Kalani 2 Shelf Leaning Desk Natural/Charcoal',
    category: 'office',
    prevPrice: '270.00',
    subCategory: 'desks',
    price: '219.00',
  },
  {
    title: 'Clyde Desk',
    category: 'office',
    prevPrice: '1,500.00',
    subCategory: 'desks',
    price: '1,199.00',
  },
  {
    title: 'Fidelma Writing Desk Black',
    category: 'office',
    prevPrice: '290.00',
    subCategory: 'desks',
    price: '229.00',
  },
  {
    title: 'Lani 2 Drawer Desk Brown',
    category: 'office',
    prevPrice: '300.00',
    subCategory: 'desks',
    price: '239.00',
  },
  {
    title: 'Omni Mara 2 Drawer Desk Taupe',
    category: 'office',
    prevPrice: '319.00',
    subCategory: 'desks',
    price: '249.00',
  },
  {
    title: 'Sidney Desk Black',
    category: 'office',
    prevPrice: '1,130.00',
    subCategory: 'desks',
    price: '929.00',
  },
  {
    title: 'Mckenna 2 Drawer Desk Taupe',
    category: 'office',
    prevPrice: '300.00',
    subCategory: 'desks',
    price: '239.00',
  },
  {
    title: 'Harkin 3 Drawer Desk Brown',
    category: 'office',
    prevPrice: '360.00',
    subCategory: 'desks',
    price: '289.00',
  },
  {
    title: 'Fidelma Writing Desk Distressed White',
    category: 'office',
    prevPrice: '290.00',
    subCategory: 'desks',
    price: '229.00',
  },
  {
    title: 'Fidelma Writing Desk Brown',
    category: 'office',
    prevPrice: '290.00',
    subCategory: 'desks',
    price: '229.00',
  },
  {
    title: 'Arlette 1 Drawer Desk Black',
    category: 'office',
    prevPrice: '220.00',
    subCategory: 'desks',
    price: '179.00',
  },
  {
    title: 'Mckenna 2 Drawer Desk Distressed White',
    category: 'office',
    prevPrice: '300.00',
    subCategory: 'desks',
    price: '239.00',
  },
  {
    title: 'Angela French Accent Desk Distressed White',
    category: 'office',
    prevPrice: '720.00',
    subCategory: 'desks',
    price: '579.00',
  },
  {
    title: 'Osiris Desk',
    category: 'office',
    prevPrice: '2,200.00',
    subCategory: 'desks',
    price: '1,799.00',
  },
  {
    title: 'Darian Acrylic Desk Black/Clear',
    category: 'office',
    prevPrice: '1,800.00',
    subCategory: 'desks',
    price: '1,499.00',
  },
  {
    title: 'Nartov Point Desk',
    category: 'office',
    prevPrice: '710.00',
    subCategory: 'desks',
    price: '579.00',
  },
  {
    title: 'Audrina Lacquer Desk White',
    category: 'office',
    prevPrice: '830.00',
    subCategory: 'desks',
    price: '669.00',
  },
  {
    title: 'Rehnuma Desk Walnut',
    category: 'office',
    prevPrice: '280.00',
    subCategory: 'desks',
    price: '219.00',
  },
  {
    title: 'Lian 2 Drawer Vanity With Mirror Natural/Brass',
    category: 'office',
    prevPrice: '480.00',
    subCategory: 'desks',
    price: '389.00',
  },
  {
    title: 'Ray Desk White Wash/Brass',
    category: 'office',
    prevPrice: '470.00',
    subCategory: 'desks',
    price: '379.00',
  },
  {
    title: 'Writers 2-Drawer Desk White',
    category: 'office',
    prevPrice: '270.00',
    subCategory: 'desks',
    price: '219.00',
  },
  {
    title: 'Odael 2 Drawer Desk Brown',
    category: 'office',
    prevPrice: '280.00',
    subCategory: 'desks',
    price: '229.00',
  },
  {
    title: 'Lian 2 Drawer Desk Natural/Brass',
    category: 'office',
    prevPrice: '480.00',
    subCategory: 'desks',
    price: '389.00',
  },
  {
    title: 'Mckenna 2 Drawer Desk Distressed Gray',
    category: 'office',
    prevPrice: '300.00',
    subCategory: 'desks',
    price: '239.00',
  },
  {
    title: 'Rodney Butterfly Desk Antique Gold',
    category: 'office',
    prevPrice: '560.00',
    subCategory: 'desks',
    price: '449.00',
  },
  {
    title: 'Remma 1 Drawer Writing Desk Brown',
    category: 'office',
    prevPrice: '260.00',
    subCategory: 'desks',
    price: '199.00',
  },
  {
    title: 'Jander Lacquer Desk Blue',
    category: 'office',
    prevPrice: '1,030.00',
    subCategory: 'desks',
    price: '819.00',
  },
  {
    title: 'Macey Desk White Wash/Brass',
    category: 'office',
    prevPrice: '470.00',
    subCategory: 'desks',
    price: '379.00',
  },
  {
    title: 'Cubic Shelving Unit',
    category: 'office',
    prevPrice: '450.00',
    subCategory: 'bookcases',
    price: '369.00',
  },
  {
    title: 'Leala Shelving Unit Walnut/Dark Gray',
    category: 'office',
    prevPrice: '150.00',
    subCategory: 'bookcases',
    price: '119.00',
  },
  {
    title: 'Zhao Bookcase White 6 Tier',
    category: 'office',
    prevPrice: '470.00',
    subCategory: 'bookcases',
    price: '379.00',
  },
  {
    title: 'Zhao Bookcase White 3 Tier',
    category: 'office',
    prevPrice: '250.00',
    subCategory: 'bookcases',
    price: '199.00',
  },
  {
    title: 'Zhao Bookcase Wenge 6 Tier',
    category: 'office',
    prevPrice: '470.00',
    subCategory: 'bookcases',
    price: '379.00',
  },
  {
    title: 'Reese Display Stand Walnut',
    category: 'office',
    prevPrice: '290.00',
    subCategory: 'bookcases',
    price: '229.00',
  },
  {
    title: 'Elway Storage Bookcase',
    category: 'office',
    prevPrice: '360.00',
    subCategory: 'bookcases',
    price: '279.00',
  },
  {
    title: 'Odelia 5 Tier Bookcase',
    category: 'office',
    prevPrice: '250.00',
    subCategory: 'bookcases',
    price: '199.00',
  },
  {
    title: 'Tiffin Bookcase Walnut',
    category: 'office',
    prevPrice: '310.00',
    subCategory: 'bookcases',
    price: '249.00',
  },
  {
    title: 'Lolland Bookcase',
    category: 'office',
    prevPrice: '510.00',
    subCategory: 'bookcases',
    price: '409.00',
  },
  {
    title: 'Alec 5 Tier Etagere',
    category: 'office',
    prevPrice: '250.00',
    subCategory: 'bookcases',
    price: '199.00',
  },
  {
    title: 'Valera Bookshelf Large',
    category: 'office',
    prevPrice: '1,900.00',
    subCategory: 'bookcases',
    price: '1,499.00',
  },
  {
    title: 'Redmond Shelf Solid Walnut Large',
    category: 'office',
    prevPrice: '3,000.00',
    subCategory: 'bookcases',
    price: '2,399.00',
  },
  {
    title: 'Ferra Gold/Mirrored Shelving Unit',
    category: 'office',
    prevPrice: '1,179.00',
    subCategory: 'bookcases',
    price: '929.00',
  },
  {
    title: 'Dixie 4 Tier Etagere',
    category: 'office',
    prevPrice: '340.00',
    subCategory: 'bookcases',
    price: '269.00',
  },
  {
    title: 'Ridge 5 Tier Etagere Gold Liquid/Rustic Oak',
    category: 'office',
    prevPrice: '920.00',
    subCategory: 'bookcases',
    price: '729.00',
  },
  {
    title: 'Zhao Bookcase Wenge 3 Tier',
    category: 'office',
    prevPrice: '250.00',
    subCategory: 'bookcases',
    price: '199.00',
  },
  {
    title: 'Gage Wood Etagere',
    category: 'office',
    prevPrice: '670.00',
    subCategory: 'bookcases',
    price: '549.00',
  },
  {
    title: 'Vermont Wood Bookshelf Brown',
    category: 'office',
    prevPrice: '1,900.00',
    subCategory: 'bookcases',
    price: '1,499.00',
  },
  {
    title: 'Albina 5 Tier Leaning Etagere Honey Brown/Charcoal',
    category: 'office',
    prevPrice: '180.00',
    subCategory: 'bookcases',
    price: '139.00',
  },
  {
    title: 'Albina 5 Tier Leaning Etagere All Black',
    category: 'office',
    prevPrice: '220.00',
    subCategory: 'bookcases',
    price: '169.00',
  },
  {
    title: 'Cuallea 5 Tier Leaning Etagere Honey Brown/Charcoal',
    category: 'office',
    prevPrice: '230.00',
    subCategory: 'bookcases',
    price: '179.00',
  },
  {
    title: 'Cuallea 5 Tier Leaning Etagere Black',
    category: 'office',
    prevPrice: '280.00',
    subCategory: 'bookcases',
    price: '219.00',
  },
  {
    title: 'Tiana Round 5 Tier Etagere White/Brass',
    category: 'office',
    prevPrice: '490.00',
    subCategory: 'bookcases',
    price: '399.00',
  },
  {
    title: 'Judson 5 Tier Etagere Black/Brass',
    category: 'office',
    prevPrice: '529.00',
    subCategory: 'bookcases',
    price: '429.00',
  },
  {
    title: 'Franco 5 Tier Etagere Gold/Clear',
    category: 'office',
    prevPrice: '520.00',
    subCategory: 'bookcases',
    price: '419.00',
  },
  {
    title: 'Cesta Wood Etagere Oak/Black',
    category: 'office',
    prevPrice: '520.00',
    subCategory: 'bookcases',
    price: '429.00',
  },
  {
    title: 'Joel 1 Drawer 5 Shelf Etagere Navy',
    category: 'office',
    prevPrice: '750.00',
    subCategory: 'bookcases',
    price: '599.00',
  },
  {
    title: 'Phoebe 3 Shelf Etagere Natural',
    category: 'office',
    prevPrice: '340.00',
    subCategory: 'bookcases',
    price: '279.00',
  },
  {
    title: 'Myles Shelf Large White',
    category: 'office',
    prevPrice: '2,000.00',
    subCategory: 'bookcases',
    price: '1,599.00',
  },
  {
    title: 'Fairfield White/Gold Accent Shelf',
    category: 'office',
    prevPrice: '420.00',
    subCategory: 'bookcases',
    price: '349.00',
  },
  {
    title: 'Myles Shelf Large Walnut',
    category: 'office',
    prevPrice: '1,800.00',
    subCategory: 'bookcases',
    price: '1,499.00',
  },
  {
    title: 'Darby 4 Tier Etagere White/Brass',
    category: 'office',
    prevPrice: '440.00',
    subCategory: 'bookcases',
    price: '349.00',
  },
  {
    title: 'Natalia Retro Mid Century Wood Etagere Oak/Black',
    category: 'office',
    prevPrice: '730.00',
    subCategory: 'bookcases',
    price: '589.00',
  },
  {
    title: 'Ricky Bookcase Dark Brown',
    category: 'office',
    prevPrice: '250.00',
    subCategory: 'bookcases',
    price: '199.00',
  },
  {
    title: 'Phoebe 2 Shelf Etagere Natural',
    category: 'office',
    prevPrice: '250.00',
    subCategory: 'bookcases',
    price: '199.00',
  },
  {
    title: 'Valera Bookshelf Small',
    category: 'office',
    prevPrice: '1,700.00',
    subCategory: 'bookcases',
    price: '1,299.00',
  },
  {
    title: 'Yara 5 Tier Leaning Etagere White',
    category: 'office',
    prevPrice: '240.00',
    subCategory: 'bookcases',
    price: '189.00',
  },
  {
    title: 'Yara 5 Tier Leaning Etagere Honey Brown/Charcoal',
    category: 'office',
    prevPrice: '230.00',
    subCategory: 'bookcases',
    price: '179.00',
  },
  {
    title: 'Yara 5 Tier Leaning Etagere Black',
    category: 'office',
    prevPrice: '240.00',
    subCategory: 'bookcases',
    price: '189.00',
  },
  {
    title: 'Cuallea 5 Tier Leaning Etagere White',
    category: 'office',
    prevPrice: '280.00',
    subCategory: 'bookcases',
    price: '229.00',
  },
  {
    title: 'Belami 5 Tier Leaning Etagere White',
    category: 'office',
    prevPrice: '320.00',
    subCategory: 'bookcases',
    price: '259.00',
  },
  {
    title: 'Albina 5 Tier Leaning Etagere Natural/Charcoal',
    category: 'office',
    prevPrice: '200.00',
    subCategory: 'bookcases',
    price: '159.00',
  },
  {
    title: 'Albina 5 Tier Leaning Etagere White',
    category: 'office',
    prevPrice: '230.00',
    subCategory: 'bookcases',
    price: '179.00',
  },
  {
    title: 'Sybella 5 Tier Etagere White/Brass',
    category: 'office',
    prevPrice: '460.00',
    subCategory: 'bookcases',
    price: '379.00',
  },
  {
    title: 'James 8-Cube Shelving Unit Dark Brown',
    category: 'office',
    prevPrice: '310.00',
    subCategory: 'bookcases',
    price: '249.00',
  },
  {
    title: 'Sloane 4 Tier Etagere Gold',
    category: 'office',
    prevPrice: '400.00',
    subCategory: 'bookcases',
    price: '319.00',
  },
  {
    title: 'Chanel 5 Tier Etagere French Gray',
    category: 'office',
    prevPrice: '429.00',
    subCategory: 'bookcases',
    price: '359.00',
  },
  {
    title: 'Haven Sideboard Cabinet White/Walnut',
    category: 'dining-room',
    prevPrice: '540.00',
    subCategory: 'sideboards-and-buffets',
    price: '429.00',
  },
  {
    title: 'Realyn 3-Drawer Sideboard Oak/Black',
    category: 'dining-room',
    prevPrice: '530.00',
    subCategory: 'sideboards-and-buffets',
    price: '429.00',
  },
  {
    title: 'Clyde Sideboard',
    category: 'dining-room',
    prevPrice: '1,800.00',
    subCategory: 'sideboards-and-buffets',
    price: '1,499.00',
  },
  {
    title: 'Sierra Sideboard Walnut',
    category: 'dining-room',
    prevPrice: '3,900.00',
    subCategory: 'sideboards-and-buffets',
    price: '3,099.00',
  },
  {
    title: 'Sumatra 2 Door 1 Shelf Chest Antique White',
    category: 'dining-room',
    prevPrice: '450.00',
    subCategory: 'sideboards-and-buffets',
    price: '369.00',
  },
  {
    title: 'Claudia 2-Door Wood Spindle Storage Cabinet Brown',
    category: 'dining-room',
    prevPrice: '450.00',
    subCategory: 'sideboards-and-buffets',
    price: '369.00',
  },
  {
    title: 'Kaiya Lacquer Buffet White',
    category: 'dining-room',
    prevPrice: '1,600.00',
    subCategory: 'sideboards-and-buffets',
    price: '1,299.00',
  },
  {
    title: 'Kaiya Lacquer Buffet Green',
    category: 'dining-room',
    prevPrice: '1,600.00',
    subCategory: 'sideboards-and-buffets',
    price: '1,299.00',
  },
  {
    title: 'Sidney Sideboard Buttermilk',
    category: 'dining-room',
    prevPrice: '1,400.00',
    subCategory: 'sideboards-and-buffets',
    price: '1,149.00',
  },
  {
    title: 'Seattle 8-Shelf Wood Shoe Cabinet Gray',
    category: 'dining-room',
    prevPrice: '340.00',
    subCategory: 'sideboards-and-buffets',
    price: '269.00',
  },
  {
    title: 'Seattle 8-Shelf Wood Shoe Cabinet Walnut',
    category: 'dining-room',
    prevPrice: '340.00',
    subCategory: 'sideboards-and-buffets',
    price: '269.00',
  },
  {
    title: 'Sidney Sideboard Black',
    category: 'dining-room',
    prevPrice: '1,400.00',
    subCategory: 'sideboards-and-buffets',
    price: '1,099.00',
  },
  {
    title: 'Deion Lacquer Buffet Blue',
    category: 'dining-room',
    prevPrice: '1,600.00',
    subCategory: 'sideboards-and-buffets',
    price: '1,299.00',
  },
  {
    title: 'Faryn Lacquer Buffet White',
    category: 'dining-room',
    prevPrice: '1,600.00',
    subCategory: 'sideboards-and-buffets',
    price: '1,299.00',
  },
  {
    title: 'Deion Lacquer Buffet Gray',
    category: 'dining-room',
    prevPrice: '1,600.00',
    subCategory: 'sideboards-and-buffets',
    price: '1,299.00',
  },
  {
    title: 'Vada Buffet Black',
    category: 'dining-room',
    prevPrice: '1,180.00',
    subCategory: 'sideboards-and-buffets',
    price: '949.00',
  },
  {
    title: 'Tristan Sideboard',
    category: 'dining-room',
    prevPrice: '2,200.00',
    subCategory: 'sideboards-and-buffets',
    price: '1,799.00',
  },
  {
    title: 'Pable 3 Door Sideboard',
    category: 'dining-room',
    prevPrice: '2,700.00',
    subCategory: 'sideboards-and-buffets',
    price: '2,199.00',
  },
  {
    title: 'Gershwin Wood Buffet Black/Brass',
    category: 'dining-room',
    prevPrice: '1,400.00',
    subCategory: 'sideboards-and-buffets',
    price: '1,099.00',
  },
  {
    title: 'Zara Diamond Sideboard Gray/Gold',
    category: 'dining-room',
    prevPrice: '1,250.00',
    subCategory: 'sideboards-and-buffets',
    price: '999.00',
  },
  {
    title: 'Talita 2 Drawer 2 Door Sideboard Greige',
    category: 'dining-room',
    prevPrice: '299.00',
    subCategory: 'sideboards-and-buffets',
    price: '239.00',
  },
  {
    title: 'Talita 2 Drawer 2 Door Sideboard Distressed Gray',
    category: 'dining-room',
    prevPrice: '340.00',
    subCategory: 'sideboards-and-buffets',
    price: '269.00',
  },
  {
    title: 'Pebbles 2 Door Sideboard Distressed White',
    category: 'dining-room',
    prevPrice: '290.00',
    subCategory: 'sideboards-and-buffets',
    price: '229.00',
  },
  {
    title: 'Pebbles 2 Door Sideboard Black',
    category: 'dining-room',
    prevPrice: '290.00',
    subCategory: 'sideboards-and-buffets',
    price: '229.00',
  },
  {
    title: 'Talita 2 Drawer 2 Door Sideboard Distressed White',
    category: 'dining-room',
    prevPrice: '340.00',
    subCategory: 'sideboards-and-buffets',
    price: '269.00',
  },
  {
    title: 'Talita 2 Drawer 2 Door Sideboard Black',
    category: 'dining-room',
    prevPrice: '340.00',
    subCategory: 'sideboards-and-buffets',
    price: '269.00',
  },
  {
    title: 'Pebbles 2 Door Sideboard Greige',
    category: 'dining-room',
    prevPrice: '290.00',
    subCategory: 'sideboards-and-buffets',
    price: '229.00',
  },
  {
    title: 'Pebbles 2 Door Sideboard Brown',
    category: 'dining-room',
    prevPrice: '290.00',
    subCategory: 'sideboards-and-buffets',
    price: '229.00',
  },
  {
    title: 'Oxygen Sideboard',
    category: 'dining-room',
    prevPrice: '2,500.00',
    subCategory: 'sideboards-and-buffets',
    price: '1,999.00',
  },
  {
    title: 'Jenny Wood Sideboard',
    category: 'dining-room',
    prevPrice: '500.00',
    subCategory: 'sideboards-and-buffets',
    price: '409.00',
  },
  {
    title: 'Eden Side Chair White',
    category: 'dining-room',
    prevPrice: '100.00',
    subCategory: 'chairs',
    price: '79.00',
  },
  {
    title: 'Poet Side Chair White',
    category: 'dining-room',
    prevPrice: '120.00',
    subCategory: 'chairs',
    price: '99.00',
  },
  {
    title: 'Peace Side Chair White',
    category: 'dining-room',
    prevPrice: '140.00',
    subCategory: 'chairs',
    price: '99.00',
  },
  {
    title: 'Sabin Wood Chair White',
    category: 'dining-room',
    prevPrice: '130.00',
    subCategory: 'chairs',
    price: '99.00',
  },
  {
    title: 'Panora Side Chair Gunmetal',
    category: 'dining-room',
    prevPrice: '150.00',
    subCategory: 'chairs',
    price: '119.00',
  },
  {
    title: 'Peace Armchair Black',
    category: 'dining-room',
    prevPrice: '150.00',
    subCategory: 'chairs',
    price: '119.00',
  },
  {
    title: 'Peace Armchair White',
    category: 'dining-room',
    prevPrice: '150.00',
    subCategory: 'chairs',
    price: '119.00',
  },
  {
    title: 'Palatina Chair White',
    category: 'dining-room',
    prevPrice: '150.00',
    subCategory: 'chairs',
    price: '119.00',
  },
  {
    title: 'Peace Side Chair Black',
    category: 'dining-room',
    prevPrice: '140.00',
    subCategory: 'chairs',
    price: '119.00',
  },
  {
    title: 'Vox Chair Dark Walnut',
    category: 'dining-room',
    prevPrice: '170.00',
    subCategory: 'chairs',
    price: '129.00',
  },
  {
    title: 'Panora Bamboo Side Chair Black',
    category: 'dining-room',
    prevPrice: '180.00',
    subCategory: 'chairs',
    price: '139.00',
  },
  {
    title: 'Panora Bamboo Side Chair Gunmetal',
    category: 'dining-room',
    prevPrice: '180.00',
    subCategory: 'chairs',
    price: '139.00',
  },
  {
    title: 'Poet Armchair White',
    category: 'dining-room',
    prevPrice: '170.00',
    subCategory: 'chairs',
    price: '139.00',
  },
  {
    title: 'Panora Bamboo Side Chair White',
    category: 'dining-room',
    prevPrice: '180.00',
    subCategory: 'chairs',
    price: '139.00',
  },
  {
    title: 'Clary Chair Clear',
    category: 'dining-room',
    prevPrice: '180.00',
    subCategory: 'chairs',
    price: '149.00',
  },
  {
    title: 'Orwen Wood Dining Chair Gray',
    category: 'dining-room',
    prevPrice: '210.00',
    subCategory: 'chairs',
    price: '169.00',
  },
  {
    title: 'Orwen Wood Dining Chair Navy',
    category: 'dining-room',
    prevPrice: '210.00',
    subCategory: 'chairs',
    price: '169.00',
  },
  {
    title: 'Calista Spindle Back Chair Off White (Set of 2)',
    category: 'dining-room',
    prevPrice: '220.00',
    subCategory: 'chairs',
    price: '169.00',
  },
  {
    title: 'Calista Spindle Back Chair Gray (Set of 2)',
    category: 'dining-room',
    prevPrice: '220.00',
    subCategory: 'chairs',
    price: '169.00',
  },
  {
    title: 'Orwen Wood Dining Chair Black',
    category: 'dining-room',
    prevPrice: '210.00',
    subCategory: 'chairs',
    price: '169.00',
  },
  {
    title: 'Paula Spindle Dining Chair Charcoal Gray (Set of 2)',
    category: 'dining-room',
    prevPrice: '230.00',
    subCategory: 'chairs',
    price: '179.00',
  },
  {
    title: 'Paula Spindle Dining Chair Off White (Set of 2)',
    category: 'dining-room',
    prevPrice: '230.00',
    subCategory: 'chairs',
    price: '179.00',
  },
  {
    title: 'Paula Spindle Dining Chair Black (Set of 2)',
    category: 'dining-room',
    prevPrice: '230.00',
    subCategory: 'chairs',
    price: '179.00',
  },
  {
    title: 'Clary Armchair Pink',
    category: 'dining-room',
    prevPrice: '230.00',
    subCategory: 'chairs',
    price: '179.00',
  },
  {
    title: 'Faith Chair Natural',
    category: 'dining-room',
    prevPrice: '230.00',
    subCategory: 'chairs',
    price: '179.00',
  },
  {
    title: 'Paula Spindle Dining Chair White (Set of 2)',
    category: 'dining-room',
    prevPrice: '230.00',
    subCategory: 'chairs',
    price: '179.00',
  },
  {
    title: 'Adam Accent Chair Brown',
    category: 'dining-room',
    prevPrice: '230.00',
    subCategory: 'chairs',
    price: '179.00',
  },
  {
    title: 'Adam Accent Chair Dark Gray',
    category: 'dining-room',
    prevPrice: '230.00',
    subCategory: 'chairs',
    price: '179.00',
  },
  {
    title: 'Paula Spindle Dining Chair Raspberry (Set of 2)',
    category: 'dining-room',
    prevPrice: '230.00',
    subCategory: 'chairs',
    price: '179.00',
  },
  {
    title: 'Paula Spindle Dining Chair Natural (Set of 2)',
    category: 'dining-room',
    prevPrice: '230.00',
    subCategory: 'chairs',
    price: '179.00',
  },
  {
    title: 'Norfolk Chair Walnut (Set of 2)',
    category: 'dining-room',
    prevPrice: '220.00',
    subCategory: 'chairs',
    price: '179.00',
  },
  {
    title: 'Gentry Dining Side Chair White',
    category: 'dining-room',
    prevPrice: '230.00',
    subCategory: 'chairs',
    price: '179.00',
  },
  {
    title: 'Gentry Dining Side Chair Gray',
    category: 'dining-room',
    prevPrice: '230.00',
    subCategory: 'chairs',
    price: '179.00',
  },
  {
    title: 'Arise Dining Side Chair Black',
    category: 'dining-room',
    prevPrice: '230.00',
    subCategory: 'chairs',
    price: '179.00',
  },
  {
    title: 'Elizabeth Dining Side Chair Walnut',
    category: 'dining-room',
    prevPrice: '230.00',
    subCategory: 'chairs',
    price: '179.00',
  },
  {
    title: 'Clary Armchair Clear',
    category: 'dining-room',
    prevPrice: '230.00',
    subCategory: 'chairs',
    price: '179.00',
  },
  {
    title: 'Blaize Dining Chair Pink/Dark Gray (Set of 2)',
    category: 'dining-room',
    prevPrice: '240.00',
    subCategory: 'chairs',
    price: '189.00',
  },
  {
    title: 'Silver Rattan Barrel Dining Chair Natural/Black',
    category: 'dining-room',
    prevPrice: '240.00',
    subCategory: 'chairs',
    price: '189.00',
  },
  {
    title: 'Lucas Retro Dining Chair Natural/Gray (Set of 2)',
    category: 'dining-room',
    prevPrice: '240.00',
    subCategory: 'chairs',
    price: '189.00',
  },
  {
    title: 'Mason Velvet Chair Gray',
    category: 'dining-room',
    prevPrice: '240.00',
    subCategory: 'chairs',
    price: '189.00',
  },
  {
    title: 'Wilder Spindle Back Dining Chair White/Natural (Set of 2)',
    category: 'dining-room',
    prevPrice: '240.00',
    subCategory: 'chairs',
    price: '189.00',
  },
  {
    title: 'Wilder Spindle Back Dining Chair Gray (Set of 2)',
    category: 'dining-room',
    prevPrice: '240.00',
    subCategory: 'chairs',
    price: '189.00',
  },
  {
    title: 'Wilder Spindle Back Dining Chair Natural (Set of 2)',
    category: 'dining-room',
    prevPrice: '240.00',
    subCategory: 'chairs',
    price: '189.00',
  },
  {
    title: 'Wilder Spindle Back Dining Chair White (Set of 2)',
    category: 'dining-room',
    prevPrice: '240.00',
    subCategory: 'chairs',
    price: '189.00',
  },
  {
    title: 'Wilder Spindle Back Dining Chair Off White (Set of 2)',
    category: 'dining-room',
    prevPrice: '240.00',
    subCategory: 'chairs',
    price: '189.00',
  },
  {
    title: 'Dorian Chair Gray',
    category: 'dining-room',
    prevPrice: '240.00',
    subCategory: 'chairs',
    price: '189.00',
  },
  {
    title: 'Faith Chair Walnut',
    category: 'dining-room',
    prevPrice: '240.00',
    subCategory: 'chairs',
    price: '189.00',
  },
  {
    title: 'Wilder Spindle Back Dining Chair Black (Set of 2)',
    category: 'dining-room',
    prevPrice: '240.00',
    subCategory: 'chairs',
    price: '189.00',
  },
  {
    title: 'Lore Round Dining Table White',
    category: 'dining-room',
    prevPrice: '870.00',
    subCategory: 'dining-tables',
    price: '699.00',
  },
  {
    title: 'Tacey Circular Dining Table White',
    category: 'dining-room',
    prevPrice: '340.00',
    subCategory: 'dining-tables',
    price: '269.00',
  },
  {
    title: 'Druid Oval Wood Top Dining Table Natural',
    category: 'dining-room',
    prevPrice: '1,300.00',
    subCategory: 'dining-tables',
    price: '999.00',
  },
  {
    title: 'Carmel Dining Table White',
    category: 'dining-room',
    prevPrice: '860.00',
    subCategory: 'dining-tables',
    price: '699.00',
  },
  {
    title: 'Lore Round Dining Table Gold/White Marble',
    category: 'dining-room',
    prevPrice: '1,130.00',
    subCategory: 'dining-tables',
    price: '899.00',
  },
  {
    title: 'Shepard Dining Table White',
    category: 'dining-room',
    prevPrice: '480.00',
    subCategory: 'dining-tables',
    price: '389.00',
  },
  {
    title: 'Druid Round Wood Top Dining Table Natural',
    category: 'dining-room',
    prevPrice: '1,700.00',
    subCategory: 'dining-tables',
    price: '1,299.00',
  },
  {
    title: 'Section Dining Table White/Gold',
    category: 'dining-room',
    prevPrice: '1,180.00',
    subCategory: 'dining-tables',
    price: '959.00',
  },
  {
    title: 'Lore Oval Dining Table Walnut',
    category: 'dining-room',
    prevPrice: '1,080.00',
    subCategory: 'dining-tables',
    price: '849.00',
  },
  {
    title: 'Lore Round Dining Table Faux Marble',
    category: 'dining-room',
    prevPrice: '960.00',
    subCategory: 'dining-tables',
    price: '779.00',
  },
  {
    title: 'Lore Oval Dining Table White',
    category: 'dining-room',
    prevPrice: '930.00',
    subCategory: 'dining-tables',
    price: '749.00',
  },
  {
    title: 'Oden Dining Table',
    category: 'dining-room',
    prevPrice: '319.00',
    subCategory: 'dining-tables',
    price: '249.00',
  },
  {
    title: 'Section Dining Table White Silver',
    category: 'dining-room',
    prevPrice: '1,130.00',
    subCategory: 'dining-tables',
    price: '929.00',
  },
  {
    title: 'Floyd Dining Table Light Brown',
    category: 'dining-room',
    prevPrice: '460.00',
    subCategory: 'dining-tables',
    price: '379.00',
  },
  {
    title: 'Park Oval Dining Table',
    category: 'dining-room',
    prevPrice: '1,600.00',
    subCategory: 'dining-tables',
    price: '1,299.00',
  },
  {
    title: 'Clement Pine Wood Dining Table Brown',
    category: 'dining-room',
    prevPrice: '1,800.00',
    subCategory: 'dining-tables',
    price: '1,399.00',
  },
  {
    title: 'Lore Round Dining Table Walnut',
    category: 'dining-room',
    prevPrice: '950.00',
    subCategory: 'dining-tables',
    price: '769.00',
  },
  {
    title: 'Woven Square Lacquer Accent Table White',
    category: 'dining-room',
    prevPrice: '319.00',
    subCategory: 'dining-tables',
    price: '259.00',
  },
  {
    title: 'Moriah Wood Dining Table',
    category: 'dining-room',
    prevPrice: '610.00',
    subCategory: 'dining-tables',
    price: '499.00',
  },
  {
    title: 'Sibel Square Dining Table Walnut',
    category: 'dining-room',
    prevPrice: '350.00',
    subCategory: 'dining-tables',
    price: '279.00',
  },
  {
    title: 'Valentino Expandable Dining Table White/Silver',
    category: 'dining-room',
    prevPrice: '1,600.00',
    subCategory: 'dining-tables',
    price: '1,249.00',
  },
  {
    title: 'Lore Faux Marble Tripod Dining Table White',
    category: 'dining-room',
    prevPrice: '810.00',
    subCategory: 'dining-tables',
    price: '649.00',
  },
  {
    title: 'Babs Dining Table Clear',
    category: 'dining-room',
    prevPrice: '260.00',
    subCategory: 'dining-tables',
    price: '199.00',
  },
  {
    title: 'Doyles Extendable Wood Dining Table Brown',
    category: 'dining-room',
    prevPrice: '1,900.00',
    subCategory: 'dining-tables',
    price: '1,499.00',
  },
  {
    title: 'Loni Folding Round Dining Table Walnut',
    category: 'dining-room',
    prevPrice: '250.00',
    subCategory: 'dining-tables',
    price: '199.00',
  },
  {
    title: 'Park Round Dining Table',
    category: 'dining-room',
    prevPrice: '1,300.00',
    subCategory: 'dining-tables',
    price: '1,049.00',
  },
  {
    title: 'Saga Round Pine Wood Dining Table Brown',
    category: 'dining-room',
    prevPrice: '1,600.00',
    subCategory: 'dining-tables',
    price: '1,299.00',
  },
  {
    title: 'Tribeca Dining Table',
    category: 'dining-room',
    prevPrice: '1,900.00',
    subCategory: 'dining-tables',
    price: '1,499.00',
  },
  {
    title: 'Adia Dining Table White/Gold',
    category: 'dining-room',
    prevPrice: '1,700.00',
    subCategory: 'dining-tables',
    price: '1,399.00',
  },
  {
    title: 'Riley Rope Oval Table Black',
    category: 'dining-room',
    prevPrice: '2,100.00',
    subCategory: 'dining-tables',
    price: '1,699.00',
  },
  {
    title: 'Rogelio Dining Table White',
    category: 'dining-room',
    prevPrice: '1,130.00',
    subCategory: 'dining-tables',
    price: '919.00',
  },
  {
    title: 'Vasco Manual Extension Dining Table Walnut',
    category: 'dining-room',
    prevPrice: '470.00',
    subCategory: 'dining-tables',
    price: '379.00',
  },
  {
    title: 'Kylie Auto Mechanism Extension Dining Table Dark Gray',
    category: 'dining-room',
    prevPrice: '569.00',
    subCategory: 'dining-tables',
    price: '459.00',
  },
  {
    title: 'Floyd Dining Table Brown',
    category: 'dining-room',
    prevPrice: '500.00',
    subCategory: 'dining-tables',
    price: '399.00',
  },
  {
    title: 'Ford Drop Leaf Dining Table Rustic Natural',
    category: 'dining-room',
    prevPrice: '610.00',
    subCategory: 'dining-tables',
    price: '489.00',
  },
  {
    title: 'Chance Ash Wood Round Dining Table Natural',
    category: 'dining-room',
    prevPrice: '1,180.00',
    subCategory: 'dining-tables',
    price: '969.00',
  },
  {
    title: 'Chance Ash Wood Rectangular Dining Table Natural',
    category: 'dining-room',
    prevPrice: '1,700.00',
    subCategory: 'dining-tables',
    price: '1,399.00',
  },
  {
    title: 'Lore Round Dining Table Gold/White',
    category: 'dining-room',
    prevPrice: '1,030.00',
    subCategory: 'dining-tables',
    price: '819.00',
  },
  {
    title: 'Tunisia Concrete Dining Table Ivory',
    category: 'dining-room',
    prevPrice: '1,400.00',
    subCategory: 'dining-tables',
    price: '1,099.00',
  },
  {
    title: 'Spool Gloss Lacquer Dining Table White',
    category: 'dining-room',
    prevPrice: '1,600.00',
    subCategory: 'dining-tables',
    price: '1,249.00',
  },
  {
    title: 'Katelyn Extension Dining Table Matte Black',
    category: 'dining-room',
    prevPrice: '299.00',
    subCategory: 'dining-tables',
    price: '239.00',
  },
  {
    title: 'Miller Dining Table Natural',
    category: 'dining-room',
    prevPrice: '449.00',
    subCategory: 'dining-tables',
    price: '359.00',
  },
  {
    title: 'Katelyn Extension Dining Table Dark Gray',
    category: 'dining-room',
    prevPrice: '299.00',
    subCategory: 'dining-tables',
    price: '239.00',
  },
  {
    title: 'Brandon Rectangle Dining Table Black',
    category: 'dining-room',
    prevPrice: '460.00',
    subCategory: 'dining-tables',
    price: '369.00',
  },
  {
    title: 'Ford Drop Leaf Dining Table Antique White',
    category: 'dining-room',
    prevPrice: '610.00',
    subCategory: 'dining-tables',
    price: '489.00',
  },
  {
    title: 'Tiana Rectangle Dining Table Walnut',
    category: 'dining-room',
    prevPrice: '490.00',
    subCategory: 'dining-tables',
    price: '399.00',
  },
  {
    title: 'Sibel Square Dining Table',
    category: 'dining-room',
    prevPrice: '350.00',
    subCategory: 'dining-tables',
    price: '279.00',
  },
  {
    title: 'Sibel Square Dining Table White',
    category: 'dining-room',
    prevPrice: '350.00',
    subCategory: 'dining-tables',
    price: '279.00',
  },
  {
    title: 'Haven Modern Dresser White/Walnut',
    category: 'bedroom',
    prevPrice: '720.00',
    subCategory: 'dressers',
    price: '579.00',
  },
  {
    title: 'Leara 6-Drawer Dresser Walnut',
    category: 'bedroom',
    prevPrice: '720.00',
    subCategory: 'dressers',
    price: '579.00',
  },
  {
    title: 'Boston Wooden 6 Drawer Dresser Brown',
    category: 'bedroom',
    prevPrice: '1,180.00',
    subCategory: 'dressers',
    price: '949.00',
  },
  {
    title: 'Kaiya 3 Drawer Chest White Wash/Gold',
    category: 'bedroom',
    prevPrice: '760.00',
    subCategory: 'dressers',
    price: '609.00',
  },
  {
    title: 'Mega 6-Drawer Dresser White/Walnut',
    category: 'bedroom',
    prevPrice: '660.00',
    subCategory: 'dressers',
    price: '529.00',
  },
  {
    title: 'Hilson 3-Drawer Chest White/Walnut',
    category: 'bedroom',
    prevPrice: '330.00',
    subCategory: 'dressers',
    price: '269.00',
  },
  {
    title: 'Thames Wood Dresser Cappuccino',
    category: 'bedroom',
    prevPrice: '950.00',
    subCategory: 'dressers',
    price: '769.00',
  },
  {
    title: 'Kaiya 3 Drawer Chest Walnut/Gold',
    category: 'bedroom',
    prevPrice: '770.00',
    subCategory: 'dressers',
    price: '619.00',
  },
  {
    title: 'Hilson 6-Drawer Dresser White/Walnut',
    category: 'bedroom',
    prevPrice: '650.00',
    subCategory: 'dressers',
    price: '519.00',
  },
  {
    title: 'Gemma 3 Drawer Dresser Walnut/Black',
    category: 'bedroom',
    prevPrice: '670.00',
    subCategory: 'dressers',
    price: '549.00',
  },
  {
    title: 'Thames Chest Black',
    category: 'bedroom',
    prevPrice: '1,230.00',
    subCategory: 'dressers',
    price: '979.00',
  },
  {
    title: 'Thames Chest White',
    category: 'bedroom',
    prevPrice: '1,230.00',
    subCategory: 'dressers',
    price: '969.00',
  },
  {
    title: 'Thames Wood Dresser White',
    category: 'bedroom',
    prevPrice: '940.00',
    subCategory: 'dressers',
    price: '759.00',
  },
  {
    title: 'Zion 3 Drawer Chest White Wash/Silver',
    category: 'bedroom',
    prevPrice: '870.00',
    subCategory: 'dressers',
    price: '699.00',
  },
  {
    title: 'Zion 3 Drawer Chest White Wash/Brass',
    category: 'bedroom',
    prevPrice: '870.00',
    subCategory: 'dressers',
    price: '699.00',
  },
  {
    title: 'Raylan 3 Drawer Chest Black/Gold/Brown',
    category: 'bedroom',
    prevPrice: '650.00',
    subCategory: 'dressers',
    price: '529.00',
  },
  {
    title: 'Macey 3 Drawer Chest White Wash/Brass',
    category: 'bedroom',
    prevPrice: '880.00',
    subCategory: 'dressers',
    price: '709.00',
  },
  {
    title: 'Macey 3 Drawer Chest White Wash/Silver',
    category: 'bedroom',
    prevPrice: '880.00',
    subCategory: 'dressers',
    price: '709.00',
  },
  {
    title: 'Lali 6 Drawer Storage Unit Black',
    category: 'bedroom',
    prevPrice: '299.00',
    subCategory: 'dressers',
    price: '239.00',
  },
  {
    title: 'Blaine 3 Drawer Chest Taupe/Black',
    category: 'bedroom',
    prevPrice: '670.00',
    subCategory: 'dressers',
    price: '539.00',
  },
  {
    title: 'Oxygen Chest',
    category: 'bedroom',
    prevPrice: '1,900.00',
    subCategory: 'dressers',
    price: '1,599.00',
  },
  {
    title: 'Trey 6 Drawer Dresser Black/Brass',
    category: 'bedroom',
    prevPrice: '1,500.00',
    subCategory: 'dressers',
    price: '1,199.00',
  },
  {
    title: 'Sidney 6 Drawer Dresser Black',
    category: 'bedroom',
    prevPrice: '1,400.00',
    subCategory: 'dressers',
    price: '1,149.00',
  },
  {
    title: 'Trey 6 Drawer Dresser Gray/Brass',
    category: 'bedroom',
    prevPrice: '1,500.00',
    subCategory: 'dressers',
    price: '1,199.00',
  },
  {
    title: 'Realyn 4-Drawer Dresser Oak/Black',
    category: 'bedroom',
    prevPrice: '590.00',
    subCategory: 'dressers',
    price: '479.00',
  },
  {
    title: 'Dixie Chest White',
    category: 'bedroom',
    prevPrice: '1,400.00',
    subCategory: 'dressers',
    price: '1,149.00',
  },
  {
    title: 'Trey 6 Drawer Dresser White/Brass',
    category: 'bedroom',
    prevPrice: '1,500.00',
    subCategory: 'dressers',
    price: '1,199.00',
  },
  {
    title: 'Hydra 6 Drawer Dresser Black',
    category: 'bedroom',
    prevPrice: '1,500.00',
    subCategory: 'dressers',
    price: '1,199.00',
  },
  {
    title: 'Pedro Shagreen 6 Drawer Dresser Gray',
    category: 'bedroom',
    prevPrice: '1,900.00',
    subCategory: 'dressers',
    price: '1,499.00',
  },
  {
    title: 'Zion 3 Drawer Chest',
    category: 'bedroom',
    prevPrice: '870.00',
    subCategory: 'dressers',
    price: '699.00',
  },
  {
    title: 'Waverly 6-Drawer Chest Light Brown',
    category: 'bedroom',
    prevPrice: '690.00',
    subCategory: 'dressers',
    price: '559.00',
  },
  {
    title: 'Randy 3 Drawer Chest Lapis Blue/Gold',
    category: 'bedroom',
    prevPrice: '729.00',
    subCategory: 'dressers',
    price: '589.00',
  },
  {
    title: 'Sidney 6 Drawer Dresser Buttermilk',
    category: 'bedroom',
    prevPrice: '1,400.00',
    subCategory: 'dressers',
    price: '1,149.00',
  },
  {
    title: 'Randy 3 Drawer Chest Black/Gold',
    category: 'bedroom',
    prevPrice: '729.00',
    subCategory: 'dressers',
    price: '589.00',
  },
  {
    title: 'Charlson 6 Drawer Dresser Black',
    category: 'bedroom',
    prevPrice: '1,500.00',
    subCategory: 'dressers',
    price: '1,199.00',
  },
  {
    title: 'Miabella 5-Drawer Chest Oak/Dark Gray',
    category: 'bedroom',
    prevPrice: '560.00',
    subCategory: 'dressers',
    price: '449.00',
  },
  {
    title: 'Gemma 3 Drawer Dresser White/White Washed',
    category: 'bedroom',
    prevPrice: '670.00',
    subCategory: 'dressers',
    price: '549.00',
  },
  {
    title: 'Gemma 3 Drawer Dresser Cream/White Washed',
    category: 'bedroom',
    prevPrice: '670.00',
    subCategory: 'dressers',
    price: '549.00',
  },
  {
    title: 'Trevor Wood Chest Chestnut',
    category: 'bedroom',
    prevPrice: '880.00',
    subCategory: 'dressers',
    price: '709.00',
  },
  {
    title: 'Blaine 3 Drawer Chest',
    category: 'bedroom',
    prevPrice: '670.00',
    subCategory: 'dressers',
    price: '539.00',
  },
  {
    title: 'Gemma 3 Drawer Dresser Black/White Washed',
    category: 'bedroom',
    prevPrice: '670.00',
    subCategory: 'dressers',
    price: '549.00',
  },
  {
    title: 'Terri 3 Drawer Chest White',
    category: 'bedroom',
    prevPrice: '510.00',
    subCategory: 'dressers',
    price: '409.00',
  },
  {
    title: 'Marcene 3 Drawer Chest Brown',
    category: 'bedroom',
    prevPrice: '550.00',
    subCategory: 'dressers',
    price: '449.00',
  },
  {
    title: 'Gemma 3 Drawer Dresser Gray/White Washed',
    category: 'bedroom',
    prevPrice: '670.00',
    subCategory: 'dressers',
    price: '549.00',
  },
  {
    title: 'Raylan 3 Drawer Chest',
    category: 'bedroom',
    prevPrice: '590.00',
    subCategory: 'dressers',
    price: '479.00',
  },
  {
    title: 'Kaiya 3 Drawer Chest Natural Walnut/Gold',
    category: 'bedroom',
    prevPrice: '680.00',
    subCategory: 'dressers',
    price: '549.00',
  },
  {
    title: 'Kaiya 3 Drawer Chest Natural/Gold',
    category: 'bedroom',
    prevPrice: '770.00',
    subCategory: 'dressers',
    price: '619.00',
  },
  {
    title: 'Macey 3 Drawer Chest',
    category: 'bedroom',
    prevPrice: '880.00',
    subCategory: 'dressers',
    price: '709.00',
  },
  {
    title: 'Erabella 2 Door Chest Light Gray Linen/Nickel/Mirror',
    category: 'bedroom',
    prevPrice: '540.00',
    subCategory: 'nightstands',
    price: '429.00',
  },
  {
    title: 'Shadi 2 Door Chest Turquoise/Mirror',
    category: 'bedroom',
    prevPrice: '570.00',
    subCategory: 'nightstands',
    price: '459.00',
  },
  {
    title: 'Lydia Silver Cap Nightstand Black',
    category: 'bedroom',
    prevPrice: '340.00',
    subCategory: 'nightstands',
    price: '269.00',
  },
  {
    title: 'Asher 2 Door Chest',
    category: 'bedroom',
    prevPrice: '590.00',
    subCategory: 'nightstands',
    price: '479.00',
  },
  {
    title: 'Lydia Gold Cap Nightstand White',
    category: 'bedroom',
    prevPrice: '340.00',
    subCategory: 'nightstands',
    price: '269.00',
  },
  {
    title: 'Lydia Silver Cap Nightstand Walnut/Gold',
    category: 'bedroom',
    prevPrice: '340.00',
    subCategory: 'nightstands',
    price: '269.00',
  },
  {
    title: 'Porter 3 Drawer Chest Slate Gray',
    category: 'bedroom',
    prevPrice: '170.00',
    subCategory: 'nightstands',
    price: '139.00',
  },
  {
    title: 'Porter 3 Drawer Chest Distressed White',
    category: 'bedroom',
    prevPrice: '170.00',
    subCategory: 'nightstands',
    price: '139.00',
  },
  {
    title: 'Gemma 2 Drawer Nightstand Walnut/White',
    category: 'bedroom',
    prevPrice: '269.00',
    subCategory: 'nightstands',
    price: '219.00',
  },
  {
    title: 'Kinsley Three Drawer Nightstand White',
    category: 'bedroom',
    prevPrice: '490.00',
    subCategory: 'nightstands',
    price: '389.00',
  },
  {
    title: 'Albert One Drawer Nightstand White',
    category: 'bedroom',
    prevPrice: '320.00',
    subCategory: 'nightstands',
    price: '259.00',
  },
  {
    title: 'Porter 3 Drawer Chest Black',
    category: 'bedroom',
    prevPrice: '199.00',
    subCategory: 'nightstands',
    price: '159.00',
  },
  {
    title: 'Gemma 2 Drawer Nightstand Walnut/Black',
    category: 'bedroom',
    prevPrice: '269.00',
    subCategory: 'nightstands',
    price: '219.00',
  },
  {
    title: 'Esther Nightstand Rustic Oak',
    category: 'bedroom',
    prevPrice: '630.00',
    subCategory: 'nightstands',
    price: '509.00',
  },
  {
    title: 'Brixton 3 Drawer Nightstand Walnut',
    category: 'bedroom',
    prevPrice: '540.00',
    subCategory: 'nightstands',
    price: '429.00',
  },
  {
    title: 'Eras 1 Drawer 1 Shelf Accent Table Brown/Black/Gold',
    category: 'bedroom',
    prevPrice: '230.00',
    subCategory: 'nightstands',
    price: '179.00',
  },
  {
    title: 'Gemma 2 Drawer Nightstand Gray/White Washed',
    category: 'bedroom',
    prevPrice: '269.00',
    subCategory: 'nightstands',
    price: '219.00',
  },
  {
    title: 'Gino 3 Drawer Mirrored Nightstand Mirror',
    category: 'bedroom',
    prevPrice: '590.00',
    subCategory: 'nightstands',
    price: '479.00',
  },
  {
    title: 'Nico 1 Drawer Wood Nightstand Light Brown',
    category: 'bedroom',
    prevPrice: '720.00',
    subCategory: 'nightstands',
    price: '579.00',
  },
  {
    title: 'Pin One Drawer Nightstand White Washed/Gold',
    category: 'bedroom',
    prevPrice: '359.00',
    subCategory: 'nightstands',
    price: '289.00',
  },
  {
    title: 'Sterling 2 Drawer Wood Nightstand Brown',
    category: 'bedroom',
    prevPrice: '980.00',
    subCategory: 'nightstands',
    price: '789.00',
  },
  {
    title: 'Izabella 3 Drawer Chest',
    category: 'bedroom',
    prevPrice: '530.00',
    subCategory: 'nightstands',
    price: '429.00',
  },
  {
    title: 'Radlin Rectangle Accent Table Distressed White',
    category: 'bedroom',
    prevPrice: '120.00',
    subCategory: 'nightstands',
    price: '99.00',
  },
  {
    title: 'Kara 2 Door Chest Champagne/Nickel/Mirror',
    category: 'bedroom',
    prevPrice: '610.00',
    subCategory: 'nightstands',
    price: '489.00',
  },
  {
    title: 'Nicolas 2 Door 1 Drawer Chest',
    category: 'bedroom',
    prevPrice: '650.00',
    subCategory: 'nightstands',
    price: '519.00',
  },
  {
    title: 'Mitchell 2 Drawer Bamboo Nightstand White',
    category: 'bedroom',
    prevPrice: '530.00',
    subCategory: 'nightstands',
    price: '429.00',
  },
  {
    title: 'Randy 3 Drawer Greek Key Nightstand White',
    category: 'bedroom',
    prevPrice: '510.00',
    subCategory: 'nightstands',
    price: '409.00',
  },
  {
    title: 'Jonco 1 Drawer Accent Table Distressed White',
    category: 'bedroom',
    prevPrice: '169.00',
    subCategory: 'nightstands',
    price: '139.00',
  },
  {
    title: 'Thames Nightstand Cappuccino',
    category: 'bedroom',
    prevPrice: '350.00',
    subCategory: 'nightstands',
    price: '279.00',
  },
  {
    title: 'Haleigh 1 Drawer Accent Table Brown',
    category: 'bedroom',
    prevPrice: '170.00',
    subCategory: 'nightstands',
    price: '139.00',
  },
  {
    title: 'Porter 3 Drawer Chest Desert Brown',
    category: 'bedroom',
    prevPrice: '170.00',
    subCategory: 'nightstands',
    price: '139.00',
  },
  {
    title: 'Haleigh 1 Drawer Accent Table Distressed Gray',
    category: 'bedroom',
    prevPrice: '130.00',
    subCategory: 'nightstands',
    price: '99.00',
  },
  {
    title: 'Pin One Drawer Nightstand Walnut/Gold',
    category: 'bedroom',
    prevPrice: '340.00',
    subCategory: 'nightstands',
    price: '269.00',
  },
  {
    title: 'Haleigh 1 Drawer Accent Table Distressed White',
    category: 'bedroom',
    prevPrice: '130.00',
    subCategory: 'nightstands',
    price: '99.00',
  },
  {
    title: 'Lydia Gold Cap Nightstand Navy',
    category: 'bedroom',
    prevPrice: '340.00',
    subCategory: 'nightstands',
    price: '269.00',
  },
  {
    title: 'Haleigh 1 Drawer Accent Table Black',
    category: 'bedroom',
    prevPrice: '170.00',
    subCategory: 'nightstands',
    price: '139.00',
  },
  {
    title: 'Zariah Modern Cross Leg End Table White',
    category: 'bedroom',
    prevPrice: '590.00',
    subCategory: 'nightstands',
    price: '479.00',
  },
  {
    title: 'Zariah Modern Cross Leg End Table Black',
    category: 'bedroom',
    prevPrice: '590.00',
    subCategory: 'nightstands',
    price: '479.00',
  },
  {
    title: 'Terri 2 Drawer Nighstand White',
    category: 'bedroom',
    prevPrice: '220.00',
    subCategory: 'nightstands',
    price: '169.00',
  },
  {
    title: 'Elliot Wood Nightstand Walnut',
    category: 'bedroom',
    prevPrice: '290.00',
    subCategory: 'nightstands',
    price: '229.00',
  },
  {
    title: 'Braith 1 Drawer Textured Nightstand Gray Walnut',
    category: 'bedroom',
    prevPrice: '180.00',
    subCategory: 'nightstands',
    price: '139.00',
  },
  {
    title: 'Beaufort 1 Drawer 1 Shelf Nightstand White/Natural',
    category: 'bedroom',
    prevPrice: '270.00',
    subCategory: 'nightstands',
    price: '219.00',
  },
  {
    title: 'Erin 2 Drawer Nightstand White/Natural',
    category: 'bedroom',
    prevPrice: '320.00',
    subCategory: 'nightstands',
    price: '249.00',
  },
  {
    title: 'Beaufort 1 Drawer 1 Shelf Nightstand Natural',
    category: 'bedroom',
    prevPrice: '270.00',
    subCategory: 'nightstands',
    price: '219.00',
  },
  {
    title: 'Bain 1 Drawer 1 Shelf Nightstand Black/Natural',
    category: 'bedroom',
    prevPrice: '270.00',
    subCategory: 'nightstands',
    price: '219.00',
  },
  {
    title: 'Bain 1 Drawer 1 Shelf Nightstand White/Natural',
    category: 'bedroom',
    prevPrice: '250.00',
    subCategory: 'nightstands',
    price: '199.00',
  },
  {
    title: 'Delia 1 Drawer 1 Door Nightstand Natural',
    category: 'bedroom',
    prevPrice: '320.00',
    subCategory: 'nightstands',
    price: '249.00',
  },
  {
    title: 'Daphne 1 Drawer 1 Door Nightstand Natural',
    category: 'bedroom',
    prevPrice: '320.00',
    subCategory: 'nightstands',
    price: '249.00',
  },
  {
    title: 'Eyre Bed Brown',
    category: 'bedroom',
    prevPrice: '230.00',
    subCategory: 'beds',
    price: '139.00',
  },
  {
    title: 'Eyre Bed White',
    category: 'bedroom',
    prevPrice: '270.00',
    subCategory: 'beds',
    price: '219.00',
  },
  {
    title: 'Adriane Upholstered Velvet Bed Midnight Blue',
    category: 'bedroom',
    prevPrice: '290.00',
    subCategory: 'beds',
    price: '229.00',
  },
  {
    title: 'Terry Fabric Platform Bed Gray',
    category: 'bedroom',
    prevPrice: '340.00',
    subCategory: 'beds',
    price: '269.00',
  },
  {
    title: 'Amelie Upholstered Fabric Bed Azure',
    category: 'bedroom',
    prevPrice: '360.00',
    subCategory: 'beds',
    price: '289.00',
  },
  {
    title: 'Amelie Upholstered Fabric Bed White',
    category: 'bedroom',
    prevPrice: '360.00',
    subCategory: 'beds',
    price: '289.00',
  },
  {
    title: 'Amelie Upholstered Fabric Bed Gray',
    category: 'bedroom',
    prevPrice: '360.00',
    subCategory: 'beds',
    price: '289.00',
  },
  {
    title: 'Amelie Upholstered Fabric Bed Beige',
    category: 'bedroom',
    prevPrice: '360.00',
    subCategory: 'beds',
    price: '289.00',
  },
  {
    title: 'Edison Bed White',
    category: 'bedroom',
    prevPrice: '430.00',
    subCategory: 'beds',
    price: '349.00',
  },
  {
    title: 'Lennon Wood Platform Bed Frame White',
    category: 'bedroom',
    prevPrice: '430.00',
    subCategory: 'beds',
    price: '349.00',
  },
  {
    title: 'Lennon Wood Platform Bed Frame Cappuccino',
    category: 'bedroom',
    prevPrice: '430.00',
    subCategory: 'beds',
    price: '349.00',
  },
  {
    title: 'Lennon Wood Platform Bed Frame Walnut',
    category: 'bedroom',
    prevPrice: '430.00',
    subCategory: 'beds',
    price: '349.00',
  },
  {
    title: 'Lennon Wood Platform Bed Frame Gray',
    category: 'bedroom',
    prevPrice: '430.00',
    subCategory: 'beds',
    price: '349.00',
  },
  {
    title: 'Alwyn Fabric Bed Gray',
    category: 'bedroom',
    prevPrice: '460.00',
    subCategory: 'beds',
    price: '369.00',
  },
  {
    title: 'Alwyn Fabric Bed Light Gray',
    category: 'bedroom',
    prevPrice: '460.00',
    subCategory: 'beds',
    price: '369.00',
  },
  {
    title: 'Alwyn Fabric Bed White',
    category: 'bedroom',
    prevPrice: '460.00',
    subCategory: 'beds',
    price: '369.00',
  },
  {
    title: 'Lester Fabric Bed Teal',
    category: 'bedroom',
    prevPrice: '460.00',
    subCategory: 'beds',
    price: '379.00',
  },
  {
    title: 'Lester Fabric Bed Light Gray',
    category: 'bedroom',
    prevPrice: '460.00',
    subCategory: 'beds',
    price: '379.00',
  },
  {
    title: 'Lester Fabric Bed Beige',
    category: 'bedroom',
    prevPrice: '460.00',
    subCategory: 'beds',
    price: '379.00',
  },
  {
    title: 'Alwyn Fabric Bed Beige',
    category: 'bedroom',
    prevPrice: '460.00',
    subCategory: 'beds',
    price: '379.00',
  },
  {
    title: 'Methow Fabric Platform Bed Gray',
    category: 'bedroom',
    prevPrice: '490.00',
    subCategory: 'beds',
    price: '399.00',
  },
  {
    title: 'Allen Fabric Platform Bed Gray',
    category: 'bedroom',
    prevPrice: '500.00',
    subCategory: 'beds',
    price: '399.00',
  },
  {
    title: 'Rosa Fabric Platform Bed Gray',
    category: 'bedroom',
    prevPrice: '500.00',
    subCategory: 'beds',
    price: '399.00',
  },
  {
    title: 'Gloria Bed Frame Brown',
    category: 'bedroom',
    prevPrice: '490.00',
    subCategory: 'beds',
    price: '399.00',
  },
  {
    title: 'Paola Metal Retro Bed White',
    category: 'bedroom',
    prevPrice: '530.00',
    subCategory: 'beds',
    price: '429.00',
  },
  {
    title: 'Paola Metal Retro Bed Black',
    category: 'bedroom',
    prevPrice: '550.00',
    subCategory: 'beds',
    price: '439.00',
  },
  {
    title: 'Paola Metal Retro Bed Antique Bronze',
    category: 'bedroom',
    prevPrice: '560.00',
    subCategory: 'beds',
    price: '449.00',
  },
  {
    title: 'Richard Bed Frame Brown/Gray',
    category: 'bedroom',
    prevPrice: '600.00',
    subCategory: 'beds',
    price: '489.00',
  },
  {
    title: 'Richard Bed Frame White/Gray',
    category: 'bedroom',
    prevPrice: '600.00',
    subCategory: 'beds',
    price: '489.00',
  },
  {
    title: 'Thaddeus Upholstered Bed Light Beige/Silver',
    category: 'bedroom',
    prevPrice: '610.00',
    subCategory: 'beds',
    price: '499.00',
  },
  {
    title: 'Blakely Upholstered Bed Light Beige',
    category: 'bedroom',
    prevPrice: '629.00',
    subCategory: 'beds',
    price: '509.00',
  },
  {
    title: 'Blakely Upholstered Bed Navy',
    category: 'bedroom',
    prevPrice: '629.00',
    subCategory: 'beds',
    price: '509.00',
  },
  {
    title: 'Lanai Platform Bed Walnut',
    category: 'bedroom',
    prevPrice: '630.00',
    subCategory: 'beds',
    price: '509.00',
  },
  {
    title: 'Seattle Wood Bed Ash Walnut',
    category: 'bedroom',
    prevPrice: '630.00',
    subCategory: 'beds',
    price: '509.00',
  },
  {
    title: 'Thaddeus Upholstered Bed Light Gray',
    category: 'bedroom',
    prevPrice: '630.00',
    subCategory: 'beds',
    price: '519.00',
  },
  {
    title: 'Thaddeus Upholstered Bed Light Beige/Brass',
    category: 'bedroom',
    prevPrice: '630.00',
    subCategory: 'beds',
    price: '519.00',
  },
  {
    title: 'Thaddeus Upholstered Bed Navy',
    category: 'bedroom',
    prevPrice: '630.00',
    subCategory: 'beds',
    price: '519.00',
  },
  {
    title: 'Thaddeus Upholstered Bed Pewter',
    category: 'bedroom',
    prevPrice: '630.00',
    subCategory: 'beds',
    price: '519.00',
  },
  {
    title: 'Gallatin Gold Finish Bed Gold',
    category: 'bedroom',
    prevPrice: '660.00',
    subCategory: 'beds',
    price: '529.00',
  },
  {
    title: 'Willa Upholstered Bed Navy',
    category: 'bedroom',
    prevPrice: '710.00',
    subCategory: 'beds',
    price: '569.00',
  },
  {
    title: 'Sonali Velvet Bed Navy',
    category: 'bedroom',
    prevPrice: '700.00',
    subCategory: 'beds',
    price: '569.00',
  },
  {
    title: 'Willa Upholstered Bed Light Gray',
    category: 'bedroom',
    prevPrice: '710.00',
    subCategory: 'beds',
    price: '569.00',
  },
  {
    title: 'Rob Wood/Synthetic Rattan Bed Ash Walnut',
    category: 'bedroom',
    prevPrice: '740.00',
    subCategory: 'beds',
    price: '599.00',
  },
  {
    title: 'Mabrey Wood/Synthetic Rattan Bed Ash Walnut',
    category: 'bedroom',
    prevPrice: '750.00',
    subCategory: 'beds',
    price: '599.00',
  },
  {
    title: 'Starburst Upholstered Velvet Bed Pewter',
    category: 'bedroom',
    prevPrice: '750.00',
    subCategory: 'beds',
    price: '609.00',
  },
  {
    title: 'Carolina Upholstered Bed Beige',
    category: 'bedroom',
    prevPrice: '770.00',
    subCategory: 'beds',
    price: '619.00',
  },
  {
    title: 'Harvey Upholstered Bed Light Gray',
    category: 'bedroom',
    prevPrice: '790.00',
    subCategory: 'beds',
    price: '629.00',
  },
  {
    title: 'Sonali Velvet Bed Pewter',
    category: 'bedroom',
    prevPrice: '820.00',
    subCategory: 'beds',
    price: '649.00',
  },
  {
    title: 'Tiffin TV Stand Walnut/White',
    category: 'living-room',
    prevPrice: '260.00',
    subCategory: 'tv-stands',
    price: '199.00',
  },
  {
    title: 'Pierce 2 Door Modular TV Unit Natural/Gold',
    category: 'living-room',
    prevPrice: '250.00',
    subCategory: 'tv-stands',
    price: '199.00',
  },
  {
    title: 'Pierce 2 Door Modular TV Unit Black/Gold',
    category: 'living-room',
    prevPrice: '250.00',
    subCategory: 'tv-stands',
    price: '199.00',
  },
  {
    title: 'Ivan 1-Door TV Stand Rustic Oak/Black',
    category: 'living-room',
    prevPrice: '250.00',
    subCategory: 'tv-stands',
    price: '199.00',
  },
  {
    title: 'Titus TV Stand Natural Gray',
    category: 'living-room',
    prevPrice: '270.00',
    subCategory: 'tv-stands',
    price: '219.00',
  },
  {
    title: 'Reese Wood TV Stand Walnut',
    category: 'living-room',
    prevPrice: '270.00',
    subCategory: 'tv-stands',
    price: '219.00',
  },
  {
    title: 'Dilan 2 Shelf 2 Door Media Stand Walnut/Black',
    category: 'living-room',
    prevPrice: '289.00',
    subCategory: 'tv-stands',
    price: '229.00',
  },
  {
    title: 'Dilan 2 Shelf 2 Door Media Stand Walnut/White',
    category: 'living-room',
    prevPrice: '289.00',
    subCategory: 'tv-stands',
    price: '229.00',
  },
  {
    title: 'Crane Open Shelf Media Stand Natural Acacia',
    category: 'living-room',
    prevPrice: '289.00',
    subCategory: 'tv-stands',
    price: '229.00',
  },
  {
    title: 'Encasa TV Stand Walnut/White',
    category: 'living-room',
    prevPrice: '290.00',
    subCategory: 'tv-stands',
    price: '229.00',
  },
  {
    title: 'Audra 2 Shelf Media Stand Walnut',
    category: 'living-room',
    prevPrice: '299.00',
    subCategory: 'tv-stands',
    price: '239.00',
  },
  {
    title: 'Orion TV Stand Natural Gray',
    category: 'living-room',
    prevPrice: '310.00',
    subCategory: 'tv-stands',
    price: '249.00',
  },
  {
    title: 'Encasa Wood TV Stand Walnut/White',
    category: 'living-room',
    prevPrice: '320.00',
    subCategory: 'tv-stands',
    price: '249.00',
  },
  {
    title: 'Beijing 2 Drawer 1 Shelf Media Stand Black/Oak/Gold',
    category: 'living-room',
    prevPrice: '319.00',
    subCategory: 'tv-stands',
    price: '249.00',
  },
  {
    title: 'Sabastian TV Stand Walnut/Dark Gray',
    category: 'living-room',
    prevPrice: '310.00',
    subCategory: 'tv-stands',
    price: '249.00',
  },
  {
    title: 'Reese TV Stand Walnut',
    category: 'living-room',
    prevPrice: '320.00',
    subCategory: 'tv-stands',
    price: '259.00',
  },
  {
    title: 'Realyn 2-Drawer TV Stand Oak/Black',
    category: 'living-room',
    prevPrice: '330.00',
    subCategory: 'tv-stands',
    price: '259.00',
  },
  {
    title: 'Shanara TV Stand White/Walnut/Black/Gold',
    category: 'living-room',
    prevPrice: '330.00',
    subCategory: 'tv-stands',
    price: '259.00',
  },
  {
    title: 'Tiffin Media Console TV Stand Walnut/White',
    category: 'living-room',
    prevPrice: '340.00',
    subCategory: 'tv-stands',
    price: '269.00',
  },
  {
    title: 'Sorrento 2 Door 1 Shelf Media Stand Distressed White',
    category: 'living-room',
    prevPrice: '349.00',
    subCategory: 'tv-stands',
    price: '279.00',
  },
  {
    title: 'Sorrento 2 Door 1 Shelf Media Stand Distressed Gray',
    category: 'living-room',
    prevPrice: '349.00',
    subCategory: 'tv-stands',
    price: '279.00',
  },
  {
    title: 'Sorrento 2 Door 1 Shelf Media Stand Brown',
    category: 'living-room',
    prevPrice: '349.00',
    subCategory: 'tv-stands',
    price: '279.00',
  },
  {
    title: 'Sorrento 2 Door 1 Shelf Media Stand Black',
    category: 'living-room',
    prevPrice: '349.00',
    subCategory: 'tv-stands',
    price: '279.00',
  },
  {
    title: 'Isabella 47" TV Stand White',
    category: 'living-room',
    prevPrice: '360.00',
    subCategory: 'tv-stands',
    price: '289.00',
  },
  {
    title: 'Ozbourne 2 Door 1 Shelf Media Stand Distressed White',
    category: 'living-room',
    prevPrice: '359.00',
    subCategory: 'tv-stands',
    price: '289.00',
  },
  {
    title: 'Ozbourne 2 Door 1 Shelf Media Stand Sand',
    category: 'living-room',
    prevPrice: '359.00',
    subCategory: 'tv-stands',
    price: '289.00',
  },
  {
    title: 'Sade 2 Shelf Media Stand Walnut/Black',
    category: 'living-room',
    prevPrice: '359.00',
    subCategory: 'tv-stands',
    price: '289.00',
  },
  {
    title: 'Sade 2 Shelf Media Stand Walnut/White',
    category: 'living-room',
    prevPrice: '359.00',
    subCategory: 'tv-stands',
    price: '289.00',
  },
  {
    title: 'Ozbourne 2 Door 1 Shelf Media Stand Brown',
    category: 'living-room',
    prevPrice: '359.00',
    subCategory: 'tv-stands',
    price: '289.00',
  },
  {
    title: 'Ozbourne 2 Door 1 Shelf Media Stand Black',
    category: 'living-room',
    prevPrice: '359.00',
    subCategory: 'tv-stands',
    price: '289.00',
  },
  {
    title: 'Esme 2 Shelf Media Stand Walnut',
    category: 'living-room',
    prevPrice: '359.00',
    subCategory: 'tv-stands',
    price: '289.00',
  },
  {
    title: 'Reese Entertainment Center TV Stand Walnut',
    category: 'living-room',
    prevPrice: '360.00',
    subCategory: 'tv-stands',
    price: '289.00',
  },
  {
    title: 'Quan 2-Door TV Stand Walnut/White',
    category: 'living-room',
    prevPrice: '370.00',
    subCategory: 'tv-stands',
    price: '289.00',
  },
  {
    title: 'Roland Entertainment Unit Distressed White',
    category: 'living-room',
    prevPrice: '369.00',
    subCategory: 'tv-stands',
    price: '299.00',
  },
  {
    title: 'Roland Entertainment Unit',
    category: 'living-room',
    prevPrice: '369.00',
    subCategory: 'tv-stands',
    price: '299.00',
  },
  {
    title: 'Ajani 2 Door 1 Shelf Media Stand Distressed White',
    category: 'living-room',
    prevPrice: '369.00',
    subCategory: 'tv-stands',
    price: '299.00',
  },
  {
    title: 'Lali 4 Drawer Media Stand Black',
    category: 'living-room',
    prevPrice: '369.00',
    subCategory: 'tv-stands',
    price: '299.00',
  },
  {
    title: 'Lali 4 Drawer Media Stand Brown',
    category: 'living-room',
    prevPrice: '369.00',
    subCategory: 'tv-stands',
    price: '299.00',
  },
  {
    title: 'Lali 4 Drawer Media Stand Distressed White',
    category: 'living-room',
    prevPrice: '369.00',
    subCategory: 'tv-stands',
    price: '299.00',
  },
  {
    title: 'Magnolia 2 Door 2 Shelf Media Stand Distressed White',
    category: 'living-room',
    prevPrice: '369.00',
    subCategory: 'tv-stands',
    price: '299.00',
  },
  {
    title: 'Magnolia 2 Door 2 Shelf Media Stand Greige',
    category: 'living-room',
    prevPrice: '369.00',
    subCategory: 'tv-stands',
    price: '299.00',
  },
  {
    title: 'Magnolia 2 Door 2 Shelf Media Stand Brown',
    category: 'living-room',
    prevPrice: '369.00',
    subCategory: 'tv-stands',
    price: '299.00',
  },
  {
    title: 'Ajani 2 Door 1 Shelf Media Stand Black/Greige',
    category: 'living-room',
    prevPrice: '369.00',
    subCategory: 'tv-stands',
    price: '299.00',
  },
  {
    title: 'Ajani Media Stand Distressed White/Honey Brown',
    category: 'living-room',
    prevPrice: '369.00',
    subCategory: 'tv-stands',
    price: '299.00',
  },
  {
    title: 'Magnolia 2 Door 2 Shelf Media Stand Black',
    category: 'living-room',
    prevPrice: '369.00',
    subCategory: 'tv-stands',
    price: '299.00',
  },
  {
    title: 'Lali 4 Drawer Media Stand Sand',
    category: 'living-room',
    prevPrice: '369.00',
    subCategory: 'tv-stands',
    price: '299.00',
  },
  {
    title: 'Gemma TV Stand Black/White Washed',
    category: 'living-room',
    prevPrice: '419.00',
    subCategory: 'tv-stands',
    price: '339.00',
  },
  {
    title: 'Gemma TV Stand Gray/White Washed',
    category: 'living-room',
    prevPrice: '419.00',
    subCategory: 'tv-stands',
    price: '339.00',
  },
  {
    title: 'Orabella Coffee Table Black/Gold',
    category: 'living-room',
    prevPrice: '150.00',
    subCategory: 'coffee-tables',
    price: '119.00',
  },
  {
    title: 'Orabella Coffee Table Silver/Gold',
    category: 'living-room',
    prevPrice: '190.00',
    subCategory: 'coffee-tables',
    price: '149.00',
  },
  {
    title: 'Woven Square Lacquer Coffee Table White',
    category: 'living-room',
    prevPrice: '190.00',
    subCategory: 'coffee-tables',
    price: '149.00',
  },
  {
    title: 'Svaha Coffee Table Dark Gray Oak/Black',
    category: 'living-room',
    prevPrice: '220.00',
    subCategory: 'coffee-tables',
    price: '169.00',
  },
  {
    title: 'Beningo Tripod Coffee Table Walnut/Black',
    category: 'living-room',
    prevPrice: '220.00',
    subCategory: 'coffee-tables',
    price: '179.00',
  },
  {
    title: 'Julie Coffee Table Antique Gold',
    category: 'living-room',
    prevPrice: '230.00',
    subCategory: 'coffee-tables',
    price: '179.00',
  },
  {
    title: 'Blagnac Coffee Table Black',
    category: 'living-room',
    prevPrice: '230.00',
    subCategory: 'coffee-tables',
    price: '189.00',
  },
  {
    title: 'Norah Tray Top Coffee Table Distressed White',
    category: 'living-room',
    prevPrice: '239.00',
    subCategory: 'coffee-tables',
    price: '189.00',
  },
  {
    title: 'Bobby 2 Drawer Coffee Table Distressed Black',
    category: 'living-room',
    prevPrice: '240.00',
    subCategory: 'coffee-tables',
    price: '189.00',
  },
  {
    title: 'Norah Tray Top Coffee Table Slate Gray',
    category: 'living-room',
    prevPrice: '239.00',
    subCategory: 'coffee-tables',
    price: '189.00',
  },
  {
    title: 'Norah Tray Top Coffee Table Desert Brown',
    category: 'living-room',
    prevPrice: '239.00',
    subCategory: 'coffee-tables',
    price: '189.00',
  },
  {
    title: 'Martin Round Glass Coffee Table',
    category: 'living-room',
    prevPrice: '240.00',
    subCategory: 'coffee-tables',
    price: '189.00',
  },
  {
    title: 'Laon Coffee Table Black/Walnut',
    category: 'living-room',
    prevPrice: '260.00',
    subCategory: 'coffee-tables',
    price: '199.00',
  },
  {
    title: 'Laon Coffee Table White/Walnut',
    category: 'living-room',
    prevPrice: '260.00',
    subCategory: 'coffee-tables',
    price: '199.00',
  },
  {
    title: 'Cullen Wood Tray Top Coffee Table',
    category: 'living-room',
    prevPrice: '260.00',
    subCategory: 'coffee-tables',
    price: '199.00',
  },
  {
    title: 'Gerby Wood Coffee Table',
    category: 'living-room',
    prevPrice: '260.00',
    subCategory: 'coffee-tables',
    price: '199.00',
  },
  {
    title: 'Jerry Wicker Storage Coffee Table Gray',
    category: 'living-room',
    prevPrice: '250.00',
    subCategory: 'coffee-tables',
    price: '199.00',
  },
  {
    title: 'Morris 2 Drawer Coffee Table Brown',
    category: 'living-room',
    prevPrice: '260.00',
    subCategory: 'coffee-tables',
    price: '199.00',
  },
  {
    title: 'Jerry Wicker Storage Coffee Table Natural',
    category: 'living-room',
    prevPrice: '250.00',
    subCategory: 'coffee-tables',
    price: '199.00',
  },
  {
    title: 'Bobby 2 Drawer Coffee Table Distressed Cream',
    category: 'living-room',
    prevPrice: '269.00',
    subCategory: 'coffee-tables',
    price: '219.00',
  },
  {
    title: 'Morris 2 Drawer Coffee Table Distressed White',
    category: 'living-room',
    prevPrice: '269.00',
    subCategory: 'coffee-tables',
    price: '219.00',
  },
  {
    title: 'Morris 2 Drawer Coffee Table Distressed Gray',
    category: 'living-room',
    prevPrice: '270.00',
    subCategory: 'coffee-tables',
    price: '219.00',
  },
  {
    title: 'Pierce Two Drawer Coffee Table Black/Gold',
    category: 'living-room',
    prevPrice: '280.00',
    subCategory: 'coffee-tables',
    price: '219.00',
  },
  {
    title: 'Ross Wood Coffee Table Black',
    category: 'living-room',
    prevPrice: '280.00',
    subCategory: 'coffee-tables',
    price: '219.00',
  },
  {
    title: 'Monroe Rattan Coffee Table Gray White Wash',
    category: 'living-room',
    prevPrice: '270.00',
    subCategory: 'coffee-tables',
    price: '219.00',
  },
  {
    title: 'Mark Chrome High Gloss Coffee Table White/Chrome',
    category: 'living-room',
    prevPrice: '270.00',
    subCategory: 'coffee-tables',
    price: '219.00',
  },
  {
    title: 'Alex Coffee Table Distressed Black',
    category: 'living-room',
    prevPrice: '270.00',
    subCategory: 'coffee-tables',
    price: '219.00',
  },
  {
    title: 'Alex Coffee Table Brown Pine',
    category: 'living-room',
    prevPrice: '270.00',
    subCategory: 'coffee-tables',
    price: '219.00',
  },
  {
    title: 'Lian Glass/Wood Coffee Table Clear/Natural',
    category: 'living-room',
    prevPrice: '260.00',
    subCategory: 'coffee-tables',
    price: '219.00',
  },
  {
    title: 'Monroe Rattan Coffee Table Natural',
    category: 'living-room',
    prevPrice: '270.00',
    subCategory: 'coffee-tables',
    price: '219.00',
  },
  {
    title: 'Knoxville Cocktail Table',
    category: 'living-room',
    prevPrice: '290.00',
    subCategory: 'coffee-tables',
    price: '229.00',
  },
  {
    title: 'Ori Faux Stone Coffee Table',
    category: 'living-room',
    prevPrice: '290.00',
    subCategory: 'coffee-tables',
    price: '229.00',
  },
  {
    title: 'Riley Cocktail Table',
    category: 'living-room',
    prevPrice: '290.00',
    subCategory: 'coffee-tables',
    price: '229.00',
  },
  {
    title: 'Beningo Tripod Coffee Table Light Gray Oak/Black',
    category: 'living-room',
    prevPrice: '290.00',
    subCategory: 'coffee-tables',
    price: '229.00',
  },
  {
    title: 'Alex Coffee Table Distressed Red Barn',
    category: 'living-room',
    prevPrice: '280.00',
    subCategory: 'coffee-tables',
    price: '229.00',
  },
  {
    title: 'Jadon Triangle Coffee Table',
    category: 'living-room',
    prevPrice: '290.00',
    subCategory: 'coffee-tables',
    price: '229.00',
  },
  {
    title: 'Rubicon Round Tray Top Coffee Table Rose Gold/Black',
    category: 'living-room',
    prevPrice: '290.00',
    subCategory: 'coffee-tables',
    price: '229.00',
  },
  {
    title: 'Russell Coffee Table White',
    category: 'living-room',
    prevPrice: '290.00',
    subCategory: 'coffee-tables',
    price: '229.00',
  },
  {
    title: 'Orlando 2 Tier Coffee Table',
    category: 'living-room',
    prevPrice: '280.00',
    subCategory: 'coffee-tables',
    price: '229.00',
  },
  {
    title: 'Ruby Rect Coffee Table',
    category: 'living-room',
    prevPrice: '300.00',
    subCategory: 'coffee-tables',
    price: '239.00',
  },
  {
    title: 'Fidelma 2 Drawer Coffee Table Black',
    category: 'living-room',
    prevPrice: '300.00',
    subCategory: 'coffee-tables',
    price: '239.00',
  },
  {
    title: 'Fidelma 2 Drawer Coffee Table Distressed White',
    category: 'living-room',
    prevPrice: '300.00',
    subCategory: 'coffee-tables',
    price: '239.00',
  },
  {
    title: 'Marcos Wood Coffee Table',
    category: 'living-room',
    prevPrice: '299.00',
    subCategory: 'coffee-tables',
    price: '239.00',
  },
  {
    title: 'Fidelma 2 Drawer Coffee Table Brown',
    category: 'living-room',
    prevPrice: '300.00',
    subCategory: 'coffee-tables',
    price: '239.00',
  },
  {
    title: 'Seamus 2 Tier Coffee Table',
    category: 'living-room',
    prevPrice: '300.00',
    subCategory: 'coffee-tables',
    price: '239.00',
  },
  {
    title: 'Ryder Coffee Table Gray/Black',
    category: 'living-room',
    prevPrice: '320.00',
    subCategory: 'coffee-tables',
    price: '249.00',
  },
  {
    title: 'Ryder Coffee Table Dark Gray/Black',
    category: 'living-room',
    prevPrice: '320.00',
    subCategory: 'coffee-tables',
    price: '249.00',
  },
  {
    title: 'Fidelma 2 Drawer Coffee Table White Washed Gray',
    category: 'living-room',
    prevPrice: '320.00',
    subCategory: 'coffee-tables',
    price: '249.00',
  },
  {
    title: 'Charbel Foldable Futon Bed Pink Velvet',
    category: 'living-room',
    prevPrice: '610.00',
    subCategory: 'sofas',
    price: '489.00',
  },
  {
    title: 'Charbel Foldable Futon Bed Navy Velvet',
    category: 'living-room',
    prevPrice: '610.00',
    subCategory: 'sofas',
    price: '489.00',
  },
  {
    title: 'Charbel Foldable Futon Bed Cognac/Chrome',
    category: 'living-room',
    prevPrice: '650.00',
    subCategory: 'sofas',
    price: '519.00',
  },
  {
    title: 'Burke Foldable Futon Bed Navy/Brown',
    category: 'living-room',
    prevPrice: '670.00',
    subCategory: 'sofas',
    price: '539.00',
  },
  {
    title: 'Burke Foldable Futon Bed Pink Velvet/Natural',
    category: 'living-room',
    prevPrice: '670.00',
    subCategory: 'sofas',
    price: '539.00',
  },
  {
    title: 'Burke Foldable Futon Bed Gray/Brown',
    category: 'living-room',
    prevPrice: '680.00',
    subCategory: 'sofas',
    price: '549.00',
  },
  {
    title: 'Elena Loveseat Blue/Natural',
    category: 'living-room',
    prevPrice: '700.00',
    subCategory: 'sofas',
    price: '559.00',
  },
  {
    title: 'Raylee Upholstered Fabric Sofa White',
    category: 'living-room',
    prevPrice: '730.00',
    subCategory: 'sofas',
    price: '599.00',
  },
  {
    title: 'Raylee Upholstered Fabric Sofa Beige',
    category: 'living-room',
    prevPrice: '730.00',
    subCategory: 'sofas',
    price: '599.00',
  },
  {
    title: 'Raylee Upholstered Fabric Sofa Azure',
    category: 'living-room',
    prevPrice: '730.00',
    subCategory: 'sofas',
    price: '599.00',
  },
  {
    title: 'Raylee Upholstered Fabric Sofa Teal',
    category: 'living-room',
    prevPrice: '730.00',
    subCategory: 'sofas',
    price: '599.00',
  },
  {
    title: 'Raylee Upholstered Fabric Sofa Gray',
    category: 'living-room',
    prevPrice: '730.00',
    subCategory: 'sofas',
    price: '599.00',
  },
  {
    title: 'Vega Faux Leather Sofa Black/Walnut',
    category: 'living-room',
    prevPrice: '770.00',
    subCategory: 'sofas',
    price: '619.00',
  },
  {
    title: 'Vega Fabric Upholstered Sofa Light Brown/Walnut',
    category: 'living-room',
    prevPrice: '770.00',
    subCategory: 'sofas',
    price: '619.00',
  },
  {
    title: 'Eventide Parisian Settee Black',
    category: 'living-room',
    prevPrice: '770.00',
    subCategory: 'sofas',
    price: '629.00',
  },
  {
    title: 'Eventide Parisian Settee Gray',
    category: 'living-room',
    prevPrice: '770.00',
    subCategory: 'sofas',
    price: '629.00',
  },
  {
    title: 'Eventide Parisian Settee Navy',
    category: 'living-room',
    prevPrice: '790.00',
    subCategory: 'sofas',
    price: '629.00',
  },
  {
    title: 'Eventide Parisian Settee Emerald',
    category: 'living-room',
    prevPrice: '790.00',
    subCategory: 'sofas',
    price: '629.00',
  },
  {
    title: 'Traverse Foldable Sofa Bed Dark Gray/Silver',
    category: 'living-room',
    prevPrice: '780.00',
    subCategory: 'sofas',
    price: '629.00',
  },
  {
    title: 'Traverse Foldable Sofa Bed Emerald Green/Silver',
    category: 'living-room',
    prevPrice: '780.00',
    subCategory: 'sofas',
    price: '629.00',
  },
  {
    title: 'Birdie Fabric Tufted Sofa Light Gray/Walnut',
    category: 'living-room',
    prevPrice: '780.00',
    subCategory: 'sofas',
    price: '629.00',
  },
  {
    title: 'Traverse Foldable Sofa Bed Navy/Brass',
    category: 'living-room',
    prevPrice: '800.00',
    subCategory: 'sofas',
    price: '649.00',
  },
  {
    title: 'Traverse Foldable Futon Bed Bllush Pink/Brass',
    category: 'living-room',
    prevPrice: '800.00',
    subCategory: 'sofas',
    price: '649.00',
  },
  {
    title: 'Traverse Foldable Sofa Bed Emerald Green/Brass',
    category: 'living-room',
    prevPrice: '800.00',
    subCategory: 'sofas',
    price: '649.00',
  },
  {
    title: 'Birdie Distressed Faux Leather Sofa Dark Brown/Walnut',
    category: 'living-room',
    prevPrice: '820.00',
    subCategory: 'sofas',
    price: '659.00',
  },
  {
    title: 'Paloma Channel Tufted Velvet Sofa Dusty Rose',
    category: 'living-room',
    prevPrice: '820.00',
    subCategory: 'sofas',
    price: '659.00',
  },
  {
    title: 'Solid Tufted Foldable Sofa Bed Navy/Silver',
    category: 'living-room',
    prevPrice: '820.00',
    subCategory: 'sofas',
    price: '669.00',
  },
  {
    title: 'Paloma Channel Tufted Velvet Sofa White',
    category: 'living-room',
    prevPrice: '840.00',
    subCategory: 'sofas',
    price: '669.00',
  },
  {
    title: 'Mac Fabric Upholstered Daybed Gray/Walnut',
    category: 'living-room',
    prevPrice: '1,130.00',
    subCategory: 'sofas',
    price: '899.00',
  },
  {
    title: 'Mac Fabric Upholstered Wood Daybed Gray/Walnut',
    category: 'living-room',
    prevPrice: '1,130.00',
    subCategory: 'sofas',
    price: '899.00',
  },
  {
    title: 'Gather Tufted Convertible Fabric Sofa Bed Azure',
    category: 'living-room',
    prevPrice: '1,130.00',
    subCategory: 'sofas',
    price: '909.00',
  },
  {
    title: 'Gather Tufted Convertible Fabric Sofa Bed Beige',
    category: 'living-room',
    prevPrice: '1,130.00',
    subCategory: 'sofas',
    price: '909.00',
  },
  {
    title: 'Antonio Upholstered Fabric Sofa White',
    category: 'living-room',
    prevPrice: '1,130.00',
    subCategory: 'sofas',
    price: '929.00',
  },
  {
    title: 'Antonio Upholstered Fabric Sofa Gray',
    category: 'living-room',
    prevPrice: '1,180.00',
    subCategory: 'sofas',
    price: '959.00',
  },
  {
    title: 'Alejandra Loveseat Stone',
    category: 'living-room',
    prevPrice: '1,249.00',
    subCategory: 'sofas',
    price: '999.00',
  },
  {
    title: 'Canton Linen Sofa Gray',
    category: 'living-room',
    prevPrice: '1,099.00',
    subCategory: 'sofas',
    price: '1,049.00',
  },
  {
    title: 'Isaiah Velvet Loveseat Cream',
    category: 'living-room',
    prevPrice: '1,300.00',
    subCategory: 'sofas',
    price: '1,049.00',
  },
  {
    title: 'Isaiah Velvet Loveseat Light Gray',
    category: 'living-room',
    prevPrice: '1,300.00',
    subCategory: 'sofas',
    price: '1,049.00',
  },
  {
    title: 'Isaiah Velvet Loveseat Blush',
    category: 'living-room',
    prevPrice: '1,300.00',
    subCategory: 'sofas',
    price: '1,049.00',
  },
  {
    title: 'Cumulus Velvet Settee Cream',
    category: 'living-room',
    prevPrice: '1,400.00',
    subCategory: 'sofas',
    price: '1,099.00',
  },
  {
    title: 'Reverence Sofa Azure',
    category: 'living-room',
    prevPrice: '1,400.00',
    subCategory: 'sofas',
    price: '1,149.00',
  },
  {
    title: 'Reverence Sofa Gray',
    category: 'living-room',
    prevPrice: '1,400.00',
    subCategory: 'sofas',
    price: '1,149.00',
  },
  {
    title: 'Reverence Sofa Sunny',
    category: 'living-room',
    prevPrice: '1,400.00',
    subCategory: 'sofas',
    price: '1,149.00',
  },
  {
    title: 'Reverence Sofa Light Gray',
    category: 'living-room',
    prevPrice: '1,400.00',
    subCategory: 'sofas',
    price: '1,149.00',
  },
  {
    title: 'Reverence Sofa Teal',
    category: 'living-room',
    prevPrice: '1,400.00',
    subCategory: 'sofas',
    price: '1,149.00',
  },
  {
    title: 'Reverence Sofa Beige',
    category: 'living-room',
    prevPrice: '1,400.00',
    subCategory: 'sofas',
    price: '1,149.00',
  },
  {
    title: 'Reverence Sofa Wheatgrass',
    category: 'living-room',
    prevPrice: '1,400.00',
    subCategory: 'sofas',
    price: '1,149.00',
  },
  {
    title: 'Pearl Upholstered Fabric Sofa Gray',
    category: 'living-room',
    prevPrice: '1,400.00',
    subCategory: 'sofas',
    price: '1,149.00',
  },
]
