import type { Metadata } from 'next'
import LocalFont from 'next/font/local'
import './globals.css'
import Navbar from '@/components/navbar'
import { Toaster } from '@/components/ui/sonner'
import { SessionProvider } from '@/lib/providers'

const roboto_serif = LocalFont({
  src: '../../public/fonts/roboto-serif-latin-normal.woff2',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${roboto_serif.className} antialiased`}>
        <Toaster richColors position="top-right" />
        <SessionProvider>
          <Navbar />
          <main>{children}</main>
        </SessionProvider>
      </body>
    </html>
  )
}
