import type { Metadata } from 'next'
import { Roboto_Serif } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/navbar'

const roboto_serif = Roboto_Serif({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${roboto_serif.className} antialiased`}>
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  )
}
