import { Toaster } from '@/components/ui/sonner'
import type { Metadata } from 'next'
import LocalFont from 'next/font/local'
import './globals.css'

const poppins = LocalFont({
  src: [
    { path: '../../public/fonts/poppins-light.ttf', weight: '300', style: 'normal' },
    { path: '../../public/fonts/poppins-regular.ttf', weight: '400', style: 'normal' },
    { path: '../../public/fonts/poppins-medium.ttf', weight: '500', style: 'normal' },
    { path: '../../public/fonts/poppins-semibold.ttf', weight: '600', style: 'normal' },
  ],
})
const calstavier = LocalFont({ src: '../../public/fonts/Calstavier.ttf', variable: '--font-calstavier' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: '/plant-logo.svg',
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} ${calstavier.variable} antialiased`}>
        <Toaster richColors position="top-right" />
        {children}
      </body>
    </html>
  )
}
